### ISSUE TITLE
TypeError: Cannot read property 'expanded' of undefined

### ISSUE THREAD

**Issue by sasidhar29** [springload/react-accessible-accordion#107]
I am getting cannot read property 'expanded' of undefined error. when i followed the steps mentioned

AccordionItemBody
Path:- /node_modules/react-accessible-accordion/dist/umd/index.js:1880
  1877 |     return item.uuid === uuid;
  1878 | });
![error](https://user-images.githubusercontent.com/13739178/41564206-bbb8568e-7317-11e8-8c85-47fc5c70e440.PNG)

  1879 | 
> 1880 | var expanded = foundItem.expanded;
  1881 | 
  1882 | var id = 'accordion__body-' + uuid;
  1883 | var ariaLabelledby = 'accordion__title-' + uuid;

**Comment by ryami333** [comment]
Gidday @sasidhar29 - thanks for your issue. Are you able to paste us the code you were using, or (even better) make a codesandbox to replicate the issue?

**Comment by vincentaudebert** [comment]
Closing due to lack of details from @sasidhar29 
Will reopen if an example is provided.
