### ISSUE TITLE
How can I expand accordion only click on the arrow icon.

### ISSUE THREAD

**Issue by abhinav2331** [springload/react-accessible-accordion#109]
Hi, 
I need help how can I expand collapse accordion on click on the arrow icon.

Please help me.

Thanks in advance.

**Comment by vincentaudebert** [comment]
Not sure I understand your problem @abhinav2331 
It's already expanding or collapsing if you click on the arrow icon.

Closing for now.

**Comment by umair-riaz-official** [comment]
I think the question is expanding the accordion "only" clicking on icon.
