### ISSUE TITLE
Accordions should not use ARIA tab roles

### ISSUE THREAD

**Issue by jasonkiss** [springload/react-accessible-accordion#111]
Accordions and tabbed interfaces have different structures and interaction patterns that make the ARIA roles for tabs inappropriate for an accordion.

The use of the tablist/tab/tabpanel roles establishes user expectations about the widget's structure and (keyboard) interaction that don't apply to accordions. Read more at https://lists.w3.org/Archives/Public/public-pfwg-comments/2013JulSep/0003.html

The fundamental structure is a heading with a nested button that controls the visibility of the content block that immediately follows it. While the use of dl/dt/dd in the current [ARIA Authoring Practices Guide accordion example](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html) can be debated, the basic structure and keyboard interaction it uses is recommended.

**Comment by vincentaudebert** [comment]
Thanks for you feedback @jasonkiss as you can see with #30 we have been mean to improve this for quite a long time now.
This is now our next priority.

**Comment by ryami333** [comment]
Closed by https://github.com/springload/react-accessible-accordion/pull/148. Thanks for your patience @jasonkiss, look out for the next release :)
