### ISSUE TITLE
Option to disable accordion expand onClick

### ISSUE THREAD

**Issue by spokzers** [springload/react-accessible-accordion#119]
Is there a way to turn off the opening and closing when clicking on the accordion in different screen sizes ?

TIA

**Comment by ryami333** [comment]
Gidday @spokzers, keep in mind that fundamentally all RAA is actually doing is toggling classes on your HTML elements. You can choose to style 'open/closed' classes at various breakpoints however you see fit.

**Comment by ryami333** [comment]
Hope this helped to answer your query @spokzers, I'm going to close this issue now due to inactivity but feel free to re-open if you still have any questions.
