### ISSUE TITLE
Add ability to expand "AccordionItem" programmatically

### ISSUE THREAD

**Issue by epotockiy** [springload/react-accessible-accordion#12]
Now we can expand `AccordionItem` only on first render, after this we can't control item expand process via props or methods.
Could you please add functionality (prop on `Accordion` or `AccorionItem`) which will allow to change expand state of `AccordionItem`

**Comment by thibaudcolas** [comment]
Hey @epotockiy, feature suggestions are always welcome and I can see why this would be desirable, but realistically we work on this project based on our own requirements at the moment, not others.

Could you provide further details on how you see this work, and once we've agreed to the approach propose a pull request implementing your requested changes?

**Comment by epotockiy** [comment]
On my current project i created local version of this component in which I realized functionality of opening via props on `Accordion` component.
I added `activeItems`  prop, which can receive array of numbers or strings.
Also I changed `preExpandedItems()` function which now look like this:
```
preExpandedItems () {
  let activeItems = []
  React.Children.map(this.props.children, (item, index) => {
    if (item.props.expanded) {
      if (this.props.accordion) {
        if (activeItems.length === 0) activeItems.push(item.props.customKey || index)
      } else {
        activeItems.push(item.props.customKey || index)
      }
    }
  })
  if (activeItems.length === 0 && this.props.activeItems.length !== 0) {
    activeItems = this.props.accordion ? [this.props.activeItems[0]] : this.props.activeItems.slice()
  }
  return activeItems
}
```
As a default array indexes are used as keys for `AccordionItem`, but now custom key could be passed in `customKey` prop. 
`activeItems` prop from `Accordion` component contains keys of opened accordion items and if all accordion items don't have expand prop, it will initialize activeItems. But expanded attributes are used for initialization at first.
Next i added `componentWillReceiveProps` function to update current local state active items on props active items changes, and added lodash isEqual method to check array content equality.
```
import _isEqual from 'lodash/fp/isEqual'
...
componentWillReceiveProps (nextProps) {
  if (!_isEqual(nextProps.activeItems, this.state.activeItems)) {
    const newActiveItems = nextProps.accordion
      ? nextProps.activeItems.length
        ? [nextProps.activeItems[0]]
        : []
      : nextProps.activeItems.slice()
    this.setState({
      activeItems: newActiveItems
    })

    nextProps.onChange(nextProps.accordion ? newActiveItems[0] : newActiveItems)
  }
}
```
Also i changed one variable initialization in `renderItems` method
```
const key = item.props.customKey || index
```

**Comment by thibaudcolas** [comment]
👌 this looks like a good solution, although it's a bit hard to review since it's not a PR. Let us know if we can help you make one.

The only thing I would be careful with is `isEqual` from lodash – not sure how big that is, I'd definitely want to assess that before adding this as a dependency.

**Comment by vincentaudebert** [comment]
Live in `v0.6.0`
