### ISSUE TITLE
How can I expand accordion only on Arrow click rather than whole row ?

### ISSUE THREAD

**Issue by antriksh-gupta** [springload/react-accessible-accordion#130]
Hi,

I want to expand my accordion only on the click of an arrow and not the whole row.

Please provide with the solution.

**Comment by nimitjain** [comment]
You can override the default functionality of AccordionItemTitle by placing onClick event:
<AccordionItemTitle onClick={() => {return false;}}>

this.state = {
            isExpanded: false,
        }

Seti Initial state of expanded as false for the AccordionItem:
<AccordionItem expanded={this.state.isExpanded}>

Put a click event on the arrow function to open/close the accordion
onClick={() => this.onToggleClick()}

onToggleClick() {
        this.setState({
            isExpanded: !this.state.isExpanded
        });
    }

**Comment by ryami333** [comment]
I will give a little more detail next time I have my laptop! Could be a couple of days sorry!

**Comment by ryami333** [comment]
OK @antriksh-gupta I've updated my response above now that I'm back with my laptop :D Hope this clears everything up for you.
