### ISSUE TITLE
How to know if the accordion item is open?

### ISSUE THREAD

**Issue by Mujaddadi** [springload/react-accessible-accordion#142]
I would like to show + and - signs to indicate that the accordion item is open. Is there anyway to know without keeping track for every click on accordion item manually? Like any callback function which can be called when the accordion state is change. There is only one onChange event which can be fired but for the whole accordion.

**Comment by ryami333** [comment]
There's currently no simple way built into the API I'm afraid. But it's a feature we're planning for the next release :) See [here](https://github.com/springload/react-accessible-accordion/issues/143)!

**Comment by ryami333** [comment]
As a _filthy hack_, you could render both icons, and then use CSS rules to hide/show the appropriate one:

```jsx

return (
    <Accordion>
        <AccordionItem
            className="foo foo--expanded"
            hideBodyClassName="foo foo--collapsed"
        >
            <AccordionItemTitle>
                Click Me!
                <Icon className="icon icon--expanded" />
                <Icon className="icon icon--collapsed" />
            </AccordionItemTitle>
            <AccordionItemBody>
                Ut duis culpa anim irure proident fugiat ad ex ut aliqua in
                culpa adipisicing laborum exercitation consectetur.
            </AccordionItemBody>
        </AccordionItem>
    </Accordion>
);
```

```sass
.foo {
    &--expanded {
        .icon--collapsed {
            display: none;
        }
    }

    &--collapsed {
        .icon--expanded {
            display: none;
        }
    }
}
```

**Comment by Mujaddadi** [comment]
Thanks for the solution and I am glad you are working on it for next release :)

**Comment by ryami333** [comment]
Deferring to https://github.com/springload/react-accessible-accordion/issues/142 for the upcoming functionality.
