### ISSUE TITLE
Proposal: API Changes - render-prop components

### ISSUE THREAD

**Issue by ryami333** [springload/react-accessible-accordion#143]
Given that the upcoming release is a major release, this is an opportunity to make backward-incompatible API changes if necessary. @michelmattos raised the problem recently that we don't expose the state of `AccordionItem` (specifically `isExpanded`) and therefore our users cannot render different icons (for example) depending on the expanded state.

I see two different ways to solve this problem:
1. We add an `AccordionItemState` render-prop component, which gives the state of the AccordionItem in context.
2. We update the `AccordionItem` component API to be a render-prop component itself, which gives its own state as a render-prop argument.

### Option 1: New `AccordionItemState` component.
```jsx
/*
 * COPY + PASTE WARNING!!
 * This is a *proposal*, not real copy+pasteable code.
*/ 

return (
    <Accordion>
        <AccordionItem>
            <AccordionItemTitle>
                Click Me!
                <AccordionItemState>
                    {isExpanded =>
                        isExpanded ? <ExpandedIcon /> : <CollapsedIcon />
                    }
                </AccordionItemState>
            </AccordionItemTitle>
            <AccordionItemBody>
                Ut duis culpa anim irure proident fugiat ad ex ut aliqua in
                culpa adipisicing laborum exercitation consectetur.
            </AccordionItemBody>
        </AccordionItem>
    </Accordion>
);
```

### Option 2: `AccordionItem` is a render-prop component.
```jsx
/*
 * COPY + PASTE WARNING!!
 * This is a *proposal*, not real copy+pasteable code.
*/ 

return (
    <Accordion>
        <AccordionItem>
            {isExpanded => (
                <React.Fragment>
                    <AccordionItemTitle>
                        Click Me!
                        {isExpanded =>
                            isExpanded ? <ExpandedIcon /> : <CollapsedIcon />
                        }
                    </AccordionItemTitle>
                    <AccordionItemBody>
                        Ut duis culpa anim irure proident fugiat ad ex ut aliqua
                        in culpa adipisicing laborum exercitation consectetur.
                    </AccordionItemBody>
                </React.Fragment>
            )}
        </AccordionItem>
    </Accordion>
);
```

---

I think that I'm leaning toward `Option #1`, as it provides a little more flexibility. And, just because we  *can* break the API doesn't mean we have to.

**Comment by ryami333** [comment]
@michelmattos I think you might be interested in this.

**Comment by michelmattos** [comment]
I also like option 1. Because it would mean a minor version since it's just adding a new API. The problem with option 2 is that it is a breaking change and would require a major version. Also, you can implement the code from option 2 using the same API from option 1:

```jsx
    <Accordion>
        <AccordionItem>
            <AccordionItemState>
                {isExpanded => (
                    <React.Fragment>
                        <AccordionItemTitle>
                            Click Me!
                            {isExpanded ? (
                                <ExpandedIcon />
                            ) : (
                                <CollapsedIcon />
                            )}
                        </AccordionItemTitle>
                        <AccordionItemBody>
                            Ut duis culpa anim irure proident fugiat ad ex ut aliqua
                            in culpa adipisicing laborum exercitation consectetur.
                        </AccordionItemBody>
                    </React.Fragment>
                )}
            </AccordionItemState>
        </AccordionItem>
    </Accordion>
```

**Comment by ryami333** [comment]
Thanks for your comments @michelmattos. Keep in mind that there is going to be a major version bump in any case (as a result of the TS migration) so we have the freedom to break the API if we _need_ to.

**Comment by stuartalexwhitehead** [comment]
Nice proposal @ryami333.

I’d also back Option 1. It’s explicit, clearly opt-in and minimises the variable scope of the state. If a Component needs access to the state, it can use `<AccordionItemState />` as high or low in the tree as required. Otherwise, it can be ignored.

Option 2 is arguably a little more succinct, but that’s about it.

**Comment by liamjohnston** [comment]
@ryami333 You said three different ways...?

**Comment by ryami333** [comment]
@stuartalexwhitehead and @michelmattos thanks for your feedback. Assuming we go with Option #1, do you think `AccordionItemState` is an appropriate name?

**Comment by FriOne** [comment]
@ryami333 could you put this into npm @next version?

**Comment by ryami333** [comment]
@FriOne we sure will be :)
