### ISSUE TITLE
Proposal: Drop legacy React support.

### ISSUE THREAD

**Issue by ryami333** [springload/react-accessible-accordion#144]
With the upcoming major release, we have the opportunity to drop support for old versions of React.

Currently, we support React 15+. In an ideal world, I would like to support only React 16.3+ because that is the release where the new Context API is introduced. At the moment, I'm having to use the clunky legacy context API. I _could_ use the new 16.3 Context API with a polyfill (`create-react-context`) but want to avoid integrating that large package into the bundle if possible. So there are two options:

### Option 1: Drop out-of-the-box support for React <16.3 but expose an API to patch it.

On the user's end, it would look like this:
```js
/*
 * COPY + PASTE WARNING!!
 * This is a *proposal*, not real copy+pasteable code.
*/ 
import { patch } from 'react-accessible-accordion';
import createContext from 'create-react-context';

patch({ createContext });
```

### Option 2: Drop out of the box support for React <16.3 and direct users to a pinned (2.X) version of `react-accessible-accordion`).

After all, 2.X is pretty stable - so we could just instruct legacy React users (in our README) to use it instead.

---

I'm leaning toward `Option #2`, but I'm interested in seeing some statistics on React version usage to help justify dropping support as far as 16.3!

**Comment by michelmattos** [comment]
I've seen some library (ie `react-redux@6.0.0`) releasing major version when they needed to drop support for older version of react (much like the option 2). Adding a new API just to support react <16.3 means increased maintenance burden.

**Comment by ryami333** [comment]
Implemented on `next` branch. Watch [here](https://github.com/springload/react-accessible-accordion/issues/168) and [here](https://github.com/springload/react-accessible-accordion/pull/188) to track progress of the associated upcoming release.
