### ISSUE TITLE
Proposal: Publish a flow definition

### ISSUE THREAD

**Issue by ryami333** [springload/react-accessible-accordion#151]
We've supported Flow with built-in types, as a feature. To maintain backward compatibility, we would need to write a Flow definition file for this project. I don't _think_ this can be automated, because there's no simple mapping between TS's `React.HTMLAttribute<HTMLDivElement>` and Flow's equivalent (for example). There hasn't been (and won't be) much churn on the package's API so I don't think this would result in a big maintenance overhead.

**Comment by grapic144** [comment]
**With it**

**Comment by ryami333** [comment]
@grapic144... Sorry?

**Comment by synecdokey** [comment]
We're using TS now, it won the type wars! 🏆
