### ISSUE TITLE
Proposal: rename `accordion` prop to `allowMultipleExpanded`

### ISSUE THREAD

**Issue by ryami333** [springload/react-accessible-accordion#152]
The accordion prop was/is a big source of confusion for users and for maintainers as it's intention is pretty ambiguous. Since [this PR](https://github.com/springload/react-accessible-accordion/pull/148) we've established that its sole purpose is to determine whether or not to allow multiple items to be expanded at one time (or conversely whether opening one item should close all of the others).

### Proposal

Rename `accordion` prop to `allowMultipleExpanded` and refactor (because it has the inverse boolean behaviour).

**Comment by catepalmer** [comment]
I've opened a branch and am working on this issue this morning - just letting everyone know so we don't end up doubling up.

**Comment by ryami333** [comment]
Closed by https://github.com/springload/react-accessible-accordion/pull/155
