### ISSUE TITLE
Proposal: Add `allowZeroExpanded` prop

### ISSUE THREAD

**Issue by ryami333** [springload/react-accessible-accordion#153]
Changes to the spec seem to indicate that it's now permitted for accordion authors to be able to choose whether their implementation permits users to close the only expanded item. I suggest that we should prevent the last one from being closable by default, but enable the alternative functionality as opt-in.

### Proposal

Add `allowZeroExpanded` prop to the Accordion (wrapper), which determines whether a 'close' action should be blocked if the item in question is currently the only one open.

**Comment by catepalmer** [comment]
I've just opened a branch to start work on this (just letting people know so we don't double up).

**Comment by ryami333** [comment]
Closed by https://github.com/springload/react-accessible-accordion/pull/160
