### ISSUE TITLE
When will the next release take place?

### ISSUE THREAD

**Issue by zerdos** [springload/react-accessible-accordion#167]
Hey peeps!

Really love your project.  We're excited to see that TypeScript support has been added.  Do you know when you might next ship a release?  We're really keen to use this but we have a hard dependency on TypeScript.

https://github.com/springload/react-accessible-accordion/issues/97

Thanks for all your work!

**Comment by johnnyreilly** [comment]
If this could happen soon that would be *amazing* 😁

**Comment by stephenmathieson** [comment]
Just noticed this myself and would definitely appreciate a release as well :)

**Comment by ryami333** [comment]
Hey everyone, thanks for your enquiry and enthusiasm. We're excited about the TS release too 😄 

I've just created [this issue](https://github.com/springload/react-accessible-accordion/issues/168) to track progress on the 3.X release.

**Comment by johnnyreilly** [comment]
Awesome! Thanks so much 😀
