### ISSUE TITLE
How to enable multiple ?

### ISSUE THREAD

**Issue by sylvainbeo** [springload/react-accessible-accordion#171]
Hi,

Thanks for this lib. Works great.

I want to enable my accordion to open multiple accordion items, but  i can't. I can't find any example to do this ? Anyone can help ? 

Thank you.

**Comment by ryami333** [comment]
In the current 2.X release, you should be able to enable this functionality by passing `accordion={false}` as prop to `Accordion`. In the upcoming 3.X release, this functionality will be more explicitly enabled by using the `allowMultipleExpanded` prop.

**Comment by sylvainbeo** [comment]
@ryami333 Thank you !
