### ISSUE TITLE
Feature Request: dynamic disabling of accordion items

### ISSUE THREAD

**Issue by archfz** [springload/react-accessible-accordion#174]
It would be nice having possibility to disable accordions items on the fly. A use case for this would be for example rendering steps as accordions items. The steps ahead are disabled while the current and before ones are enabled. One can navigate to previous step and thus disbling the next ones.

It was implemented here but got closed https://github.com/springload/react-accessible-accordion/pull/131#issuecomment-458320393

**Comment by ryami333** [comment]
Gidday @archfz, thanks for your issue. To frame my response to this feature request, I'd like to refer back to this part of my response to that closed PR:

> The concept of 'disabling' an accordion is not one which is described by any of the WAI ARIA spec, and therefore I believe it sits outside of the scope of this project. My personal opinion is that users who are trying to disable their accordions for any reason might be doing so against best-practice - almost like a "code-smell". As a matter of principle, I feel like this project should not go out of its way to provide mechanisms for users to bypass the internal behaviours of this package, which have been fairly rigorously asserted to be spec-compliant.

And to give a little more context, here's the WAI ARIA high-level description of an Accordion:

> An accordion is a vertically stacked set of interactive headings that each contain a title, content snippet, or thumbnail representing a section of content. The headings function as controls that enable users to reveal or hide their associated sections of content. Accordions are commonly used to reduce the need to scroll when presenting multiple sections of content on a single page.

In my personal opinion, your use-case does not meet this criteria for an Accordion. It's only "interactive" in the sense that the panels contain forms (I presume), but the accordion itself isn't (Ie. "headings function as controls" is not true). I think you probably require a considered implementation of multiple and various accessible concepts, including-but-not-only [disclosures](https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure).

I'm going to leave this issue open for a little while, to see if anyone else would like to propose any valid use-cases.

**Comment by paddotk** [comment]
One way I can think of is to manage the disabling with state, and replacing any AccordionItem with a div with the same styling (making it look like it's an AccordionItem), rather than actually disabling it. I haven't tested this properly but it seems that putting a div in an Accordion works.

For example, something like
```
const accordionItem1 = this.state.disabled[1]
  ? <AccordionItem>
       <AccordionTitle>Title</AccordionTitle>
       <AccordionBody>Hello</AccordionBody>
     </AccordionItem>
  : <div className="fakeAccordionItem">Title</div>;

return (
  <Accordion>
    {accordionItem1}
  </Accordion>
);
```

**Comment by ryami333** [comment]
@paddotk that is a 'workaround', not a 'use-case'.

And I will reiterate, that if your implementation necessitates this pattern, then it is probably not an 'accordion' (by WAI-ARIA's definition, anyway).

**Comment by pretentiousgit** [comment]
Hello!

I like having accessible accordions when they're needed, and Disabled is a valid use case in web-based video games, where we need to do things like offer some options but not others, and hint at their presence. There are tons of workarounds for this, but it would be _much_ easier and better to have a disabled functionality built into react-accessible-accordion - you guarantee the accessibility when turned on, your users guarantee other alternatives.

The fact of there being an aria-disabled key at all implies that sometimes disabled elements are a thing that happens on the internet, it would be great to support that even if it seems to fall outside the WAI-Aria spec right now.

**Comment by ryami333** [comment]
@pretentiousgit thanks for your feedback, but I think your use-case effectively boils down to "my application only needs to be accessible _some_ of the time" which goes against the [core principals](https://github.com/springload/react-accessible-accordion/blob/master/CONTRIBUTING.md#project-principles) of the project.

**Comment by holloway** [comment]
Hi, we have now added a prop to control accordions. Use it carefully!

https://github.com/springload/react-accessible-accordion#dangerouslysetexpanding-boolean-optional

**Comment by mkamka** [comment]
There is a typo in the Readme. It should be dangerouslySetExpanded as according to code!

**Comment by pmourer** [comment]
I noticed the above as well, and am wondering if this prop even works? changing it's value once the accordion item is mounted does not seem to have any effect... does this only work on mount.. ?
