### ISSUE TITLE
Add role on node

### ISSUE THREAD

**Issue by asicfr** [springload/react-accessible-accordion#18]
To fully respect accessbility contraintes, i have to add some properties on nodes : 
- Accordion -> role="tablist"
- AccordionItemTitle -> aria-selected="true" when element is selected
- AccordionItemTitle -> aria-selected="false" otherwise
- AccordionItemBody -> aria-labelledby="[ID_tab]"
Is it possible to add that please ?

**Comment by thibaudcolas** [comment]
Hey @asicfr, thanks for the bug report. 

From what I understand,

- Accordion -> `role="tablist"` could be added in this component without any further logic
- AccordionItemTitle -> `aria-selected` – does this replace `aria-expanded`, or should we set the two attributes? 
AccordionItemBody -> aria-labelledby="[ID_tab]" could be added if ids are provided for each tab by the user.

Would you be willing to start a pull request with those changes?

**Comment by vincentaudebert** [comment]
Thanks a lot @asicfr 
Really precious advice.

Any chance you could review the pull request I just made https://github.com/springload/react-accessible-accordion/pull/19

To test the code I just made the branch `fix/18`
Let me know if it's matching your expectations.
