### ISSUE TITLE
OnClick event not fire on AccordionItem child

### ISSUE THREAD

**Issue by heybriancheung** [springload/react-accessible-accordion#187]
<AccordionItem uuid="two">
             <AccordionItemTitle><div>Title</div></AccordionItemTitle>
             <AccordionItemBody>
                         <div><input type="button" onClick={alert('try')} value="Click" /></div>
             </AccordionItemBody>
    </AccordionItem>

The above code won't work. The button won't fire alert. Is this react component only intended for read-only data?

**Comment by ryami333** [comment]
Gidday @heybriancheung, thanks for your issue. It appears that you have written some invalid JSX markup, which is why your example is not working. Try replacing `onClick={alert('try')}` with `onClick={() => alert('try')}`. Cheers!
