### ISSUE TITLE
Question - TypeScript supported?

### ISSUE THREAD

**Issue by paddotk** [springload/react-accessible-accordion#190]
Github says this library consists of 90% TypeScript code, but when I install this no TS declaration file can be found. Is this included in the lib or available elsewhere? I tried adding `@types/react-accessible-accordion` but that doesn't seem to exist.

**Comment by ryami333** [comment]
Gidday @paddotk - we've migrated from Flow to TS for an upcoming release, which you can track progress of [here](https://github.com/springload/react-accessible-accordion/issues/168). We've got a couple of little spec-compliance issues to iron out before we publish it, but TS types will be built-in once we do 😃
