### ISSUE TITLE
Expand conditional className on AccordionItem

### ISSUE THREAD

**Issue by adambowles** [springload/react-accessible-accordion#204]
I'm aware `AccordionItemState` component is intended to replace `hideBodyClassName` prop. As far as I can tell, `AccordionItemState` cannot be rendered above an `AccordionItem` so I can't apply a conditional `className` prop to an `AccordionItem`.

Maybe I'm looking at this the wrong way, the end goal is to render the accordion 100% height of parent container. I had implemented this in v2 with `display: flex` on `Accordion` and `flex: 1` on whichever `AccordionItem` was expanded via `hideBodyClassName`.

Current code:
```jsx
import * as React from 'react';

import {
  Accordion,
  AccordionItem,
  AccordionItemButton,
  AccordionItemHeading,
  AccordionItemPanel,
  AccordionItemState,
} from 'react-accessible-accordion';

interface Props {
  items?: Array<{
    id: string;
    // ...
  }>
}

export default class MyAccordionFacade extends React.Component<Props> {
  public render(): JSX.Element {
    return (
      <Accordion
        className='accordion'
        preExpanded={[this.props.items[0].id] || []}
      >
        {this.props.items.map((item) => (
          <AccordionItem
            className='accordion_item'
            key={item.id}
            uuid={item.id}
          >
            <AccordionItemState>
              {({ expanded }) => (
                <React.Fragment>
                  <AccordionItemHeading className='accordion_item_heading'>
                    <AccordionItemButton className='accordion_item_button'>
                      // ...
                    </AccordionItemButton>
                  </AccordionItemHeading>

                  <AccordionItemPanel
                    className={
                      expanded
                        ? 'accordion_item_panel_expanded'
                        : 'accordion_item_panel'
                    }
                  >
                    // ...
                  </AccordionItemPanel>
                </React.Fragment>
              )}
            </AccordionItemState>
          </AccordionItem>
        ))}
      </Accordion>
    );
  }
}
```

What I'd like to do (notice that `AccordionItemState` wraps `AccordionItem`). This results in nothing rendered, with no errors in console:
```jsx
import * as React from 'react';

import {
  Accordion,
  AccordionItem,
  AccordionItemButton,
  AccordionItemHeading,
  AccordionItemPanel,
  AccordionItemState,
} from 'react-accessible-accordion';

interface Props {
  items?: Array<{
    id: string;
    // ...
  }>
}

export default class MyAccordionFacade extends React.Component<Props> {
  public render(): JSX.Element {
    return (
      <Accordion
        className='accordion'
        preExpanded={[this.props.items[0].id] || []}
      >
        {this.props.items.map((item) => (
          <AccordionItemState key={item.id}>
            {({ expanded }) => (
              <AccordionItem
                className={
                  expanded
                    ? 'accordion_item_expanded'
                    : 'accordion_item'
                }
                uuid={item.id}
              >
                <AccordionItemHeading className='accordion_item_heading'>
                  <AccordionItemButton className='accordion_item_button'>
                    // ...
                  </AccordionItemButton>
                </AccordionItemHeading>

                <AccordionItemPanel
                  className={
                    expanded
                      ? 'accordion_item_panel_expanded'
                      : 'accordion_item_panel'
                  }
                >
                  // ...
                </AccordionItemPanel>
              </AccordionItem>
            )}
          </AccordionItemState>
        ))}
      </Accordion>
    );
  }
}
```

**Comment by ryami333** [comment]
Gidday @adambowles, is there any reason you can't do what you were doing before (ie. "display: flex on Accordion and flex: 1")? I understand that you were applying `flex: 1` only to the currently expanded item, but you don't really need to be that specific - if the item is collapsed (has `hidden` attribute -> has `display: none`) then it doesn't matter what its `flex` value is.

**Comment by ryami333** [comment]
Gidday @adambowles - thanks for your issue! That's an interesting use-case 🤔We might need to re-implement conditional `classNames` in order to solve it!

**Comment by adambowles** [comment]
Whether it's by a className-like prop, or via exposing an `expanded` bool somehow, that's good to hear! I think an `expanded` bool would be best as it closer matches the existing API, but I understand that `AccordionItemState`'s current implementation makes that tricky.

I think that `AccordionItem` should be able to know its expanded state, even if it's not able to control it

**Comment by adambowles** [comment]
Any movement on this?

**Comment by Dobby89** [comment]
This is an essential feature.

**Comment by gcosgreave-us** [comment]
Still waiting for this...?

**Comment by synecdokey** [comment]
Bit of news: Version 3.1.0 has just been released and offers an `activeClassName` prop that will be used when the `AccordionItem` is expanded! ✨

Considering this solved, please let us know if this doesn't cover your use case!
