### ISSUE TITLE
controlled expand accordion

### ISSUE THREAD

**Issue by niyaza3** [springload/react-accessible-accordion#209]
I am using this accordion instead of multiselect

Eg: 
1. South Africa (AccordionItemHeading)
List of companies (AccordionItemPanel)

2. India (AccordionItemHeading)
List of companies (AccordionItemPanel)

There is a  text box with filter also , when user types the company name in the filter if the company name present in any of the countries it should be expanded.

The dynamic preExpanded={[...openDefault]} insertion to openDefault isn't working

`

**Comment by ryami333** [comment]
Gidday @niyaza3, thanks for your issue 😃. The key to the name of the `preExpanded` prop lies in the "pre". Unfortunately controlled accordions are not a supported pattern, and the `preExpanded` prop is only provided as a way to set the _initial_ expanded state. See [here](https://github.com/springload/react-accessible-accordion/issues/174#issuecomment-458333906) for explanation and justification.

Cheers!
