### ISSUE TITLE
Pre-expanded multiple items on mount

### ISSUE THREAD

**Issue by nostreboR5** [springload/react-accessible-accordion#210]
I want to pre-expand multiple items on mount while I enabled allowMultipleExpanded to true and allowZeroExpanded to true.  Can you please give a sample code to chive that?

**Comment by roshan605** [comment]
https://codesandbox.io/embed/react-accordion-expand-test-lflmy

Check this solution

**Comment by ryami333** [comment]
Hi @nostreboR5, thanks for your issue. What have you tried? If you check the Readme, you'll find documentation for the `preExpanded` prop, and if you check the demo you can see it in action.

**Comment by roshan605** [comment]
> 
> 
> Hi @nostreboR5, thanks for your issue. What have you tried? If you check the Readme, you'll find documentation for the `preExpanded` prop, and if you check the demo you can see it in action.
Problem is preExpanded works only in the first render. after that if we change the preExpanded it does not work. 
I find this workaround for this.

https://codesandbox.io/embed/react-accordion-expand-test-new-20vc1

**Comment by ryami333** [comment]
> Problem is preExpanded works only in the first render

Yes, that is by design, [see here](https://github.com/springload/react-accessible-accordion/issues/174) for justification. As far as I could tell, the OP was not asking how to programatically change the accordion state anyway.

**Comment by roshan605** [comment]
> > Problem is preExpanded works only in the first render
> 
> Yes, that is by design, [see here](https://github.com/springload/react-accessible-accordion/issues/174) for justification. As far as I could tell, the OP was not asking how to programatically change the accordion state anyway (as indicated by the title "... on mount").

ok ill check
