### ISSUE TITLE
Finding contents with CTRL + F

### ISSUE THREAD

**Issue by Meberem** [springload/react-accessible-accordion#211]
I have a number of nested accordions which is working great, thanks! 

I would like to be able to search the contents of the accordions using the "Find on page" features of various browsers (CTRL + F), but I am a bit stuck. I was thinking of intercepting the find call and manually expanding accordions but I'm not sure that will work based on [the item in the readme](https://github.com/springload/react-accessible-accordion#how-do-i-manually-control-the-expanded-state-of-an-item), do you have any advice on how to acomplish this?

**Comment by ryami333** [comment]
Gidday @Meberem, thanks for your issue. Sorry, but at this time we don't support programmatic control of the expanded state of accordion items, as we feel that if fights against the principals of an accessible accordion. Besides that, the native browser search feature does not have a Javascript API with which to bind events to, for example. Hidden content is, by definition, hidden to search.
