### ISSUE TITLE
Unable to Use Components in Storybook

### ISSUE THREAD

**Issue by eemp** [springload/react-accessible-accordion#213]
Hello,

I am using [Storybook](https://storybook.js.org/) to prototype some work.  I noticed that when I attempted to use this package with the example in the README, simple expand/collapse functionality was not working in Storybook.  I figured this was simply a problem of the combination of Storybook and this package.  I was able to verify that I could quickly spin up create-react-app and have the same example work.  Additionally, I was also able to confirm version 2.4.5 also works fine in Storybook.  So it's just the latest major version that's problematic in Storybook.

To reproduce:

* get storybook react going
* install this package@3.0.0
* take the example in the readme and wrap in a story

I did some quick debugging without any luck but did notice that the AccordionItem Provider values were simply not updating.  I understand if support within Storybook is not something the maintainers want to currently deal with - in that case, feel free to close the issue.  Perhaps, another user is able to figure out a solution/workaround and might use this forum.

Thanks!

**Comment by ryami333** [comment]
Hi @eemp, thanks for your issue. Which version of Storybook are you using?

**Comment by ryami333** [comment]
And can you confirm that you are using a compatible version of React (16.3+)?

**Comment by eemp** [comment]
Sorry about that.  Here's some additional info on versions:

```
@storybook/react: ^5.0.10
...
"react": "^16.6.3"
```

I can look to find some spare time and setup a quick minimal repo as an example to reproduce.

**Comment by ryami333** [comment]
That would be good, thanks @eemp. I can't really debug this otherwise.

**Comment by eemp** [comment]
Upon looking into it further, I found that I was unable to reproduce in a minimal example which means that the problem is likely specific to our ecosystem.  Sorry about wasting your time.  Closing.
