### ISSUE TITLE
Accessible accordion is not loading in iphone

### ISSUE THREAD

**Issue by sarlasankar** [springload/react-accessible-accordion#215]
Accordion Item is not loading in iphone or safari browser? any help?

**Comment by ryami333** [comment]
Hi @sarlasankar could you please provide a minimal reproducible case? Our [demo page](https://springload.github.io/react-accessible-accordion/) _does_ work in Safari, so I'm going to need far more details in order to try and help you troubleshoot this.

**Comment by ryami333** [comment]
Given that I can't reproduce this issue then I highly suspect that the problem lies in the implementation, rather than with a library defect. Closing in absence of a reproducible case and/or more specific details.
