### ISSUE TITLE
Multiple Accordions: AccordionItemButton duplicate ID - (WCAG 2.0 4.1.1)

### ISSUE THREAD

**Issue by koltclassic** [springload/react-accessible-accordion#225]
Hello!

I'm currently attempting to render out two unique `<Accordion>` components, each having their own `<AccordionItem>`s, etc. as children. Each `<AccordionItemButton>` in its respective accordion has an ID of `id="accordion__heading-0"`, `id="accordion__heading-1"`, etc. which is throwing a warning for duplicate IDs on the same page. I've attempted to overwrite the ID of each `<AccordionItemButton>` to something more unique, but to no avail. 

Do you have any recommendations for how to best handle this? I'm happy to provide any additional information as needed. Thank you for the help!

EDIT: [here](https://www.w3.org/WAI/WCAG21/quickref/#parsing) is a link to 4.1.1 for reference

**Comment by glidej** [comment]
I work with @koltclassic and we figured this out after some digging. If a `uuid` isn't specified when you declare your `<AccordionItem>`, it falls back to a simple 0-based index (hence `accordion__heading-0`). 

The simplest way to get around this is to pass a `uuid` as you would a `key` in an iterable React component.

```
<Accordion>
    <AccordionItem uuid={'foo'}> ... </AccordionItem>
    <AccordionItem uuid={'bar'}> ... </AccordionItem>
    <AccordionItem uuid={'baz'}> ... </AccordionItem>
</Accordion>
```

This will create an eventual id that looks something like, `accordion__heading-foo`. Unlike `key`, however, there are [strict rules](https://www.w3.org/TR/html4/types.html#type-id) about which characters are allowed to form an `id`, so be careful about what you put in there.
