### ISSUE TITLE
Additional Components along with AccordionItemButton

### ISSUE THREAD

**Issue by santosh898** [springload/react-accessible-accordion#228]
Sometimes AccordionHeading many need to contain elements that pourposefully should'nt trigger expand.Currently AccordionHeading is expecting **only** AccordionItemButton.

**Is there any problem with having N-number of components in Heading?**

**Comment by ryami333** [comment]
Gidday @santosh898, thanks for your query. Here is the relevant excerpt from the aria spec:

> The button element is the only element inside the heading element. That is, if there are other visually persistent elements, they are not included inside the heading element.

So the short-answer is _no_. You must nest `AccordionItemButton` directly beneath `AccordionItemHeading` and it must be the only child on `AccordionItemHeading`.

However! The `AccordionItem` component may contain arbitrary content, so you've got a little more creative freedom there to create non-clickable elements.

```jsx
<AccordionItem>
  <span>This span sits outside the 'AccordionItemHeading' so it's not a click-trigger!</span>
  <AccordionItemHeading>
    <AccordionItemButton>
      What is the meaning of life?
    </AccordionItemButton>
  </AccordionItemHeading>
</AccordionItem>
```

Hope that helps 😄

**Comment by ryami333** [comment]
Closing this issue because I think I've addressed your query, but feel free to discuss further!

**Comment by dpikt** [comment]
@ryami333 question related to this- if the `AccordionItemHeading` can only ever have an `AccordionItemButton` as a child, what's the factor keeping them from being combined into a single component? Is it to reflect the underlying markup more clearly, or to allow finer-grained control over classnames, or another reason?

**Comment by ryami333** [comment]
@dpikt yep, it's both of those things.
