### ISSUE TITLE
Close expanded accordion item on click on the same heading.

### ISSUE THREAD

**Issue by roger-guajardo** [springload/react-accessible-accordion#229]
Is it implemented that the accordion expanded item can't be close other than just clicking another accordion? I want to be able to close the accordion item I just opened by pressing it again.

**Comment by manojkumar3692** [comment]
did u find out ?? is it possible @roger-guajardo

**Comment by kolaarunkumar** [comment]
Do we have any solution @roger-guajardo @manojkumar3692 ?
