### ISSUE TITLE
how to disable the out line when you click button?

### ISSUE THREAD

**Issue by craigcosmo** [springload/react-accessible-accordion#231]
how to disable the out line when you click button?

**Comment by ryami333** [comment]
Hi there @craigcosmo, thanks for your issue. The outline around buttons and links on the web are not added by React Accessible Accordion - they're added by your browser whenever `:focus` is applied to them. Some people like to disable those outlines with CSS but that's generally "bad practice" for accessibility reasons - users should be able to use the keyboard to "tab" through your website and be able to see which link/button is currently focussed.

I find that a nice compromise is to use a library like [`what-input`](https://www.npmjs.com/package/what-input) to remove those outline if (and only if) the user's input is detected to be mouse-based (or touch-based). In combination with that library I typical use styles like this:

```
[data-whatinput='mouse'] :focus,
[data-whatinput='touch'] :focus {
    outline: none;
}
```

Hope that helps!
