### ISSUE TITLE
Is there a way to know the accordion item state in onChange method on Accordion?

### ISSUE THREAD

**Issue by vikasgarghb** [springload/react-accessible-accordion#236]
Instead of using `AccordionItemState`, is there a way to know that state in `onChange` method for `Accordion`?

**Comment by katie-day** [comment]
You can use the `onChange` method which gets passed an array of `uuid`'s of the expanded `AccordionItem`'s.
https://github.com/springload/react-accessible-accordion#onchange--string--void-optional 

Does that work for what you need?
