### ISSUE TITLE
Is there a way I can control the speed of accordion's open and close animation?

### ISSUE THREAD

**Issue by goongoguma** [springload/react-accessible-accordion#242]
Thanks for the great library I love it.

Just wondering, is there a way I can slow down or speed up the animation of react-accessible-accordion when I click the button?

**Comment by holloway** [comment]
Hey @goongoguma sorry for the delay in response, are you using the `fancy-example.css` styling?

**Comment by mwshepherd** [comment]
Is there a way to animate the accordion item panel on close? It seems the library just turns the display to hidden which can't be animated with just css.

**Comment by katie-day** [comment]
@mwshepherd, not currently unfortunately. For accessibility reasons we have chosen to use `hidden` when items are  closed, however I will leave this issue open to discuss with other contributors about possible changes. Thanks.

**Comment by thomas-nordlund** [comment]
+1 Love this library, especially that accessibility is front-and-center but it definitely be a nice to have to be able to animate the accordion items etc.

**Comment by synecdokey** [comment]
Sadly, using hidden is necessary to ensure full compatibility with a wide array of assistive technology. You should be able to add an animate property to the `AccordionPanel`, which has limitations, but the best you can achieve with the pattern we employ.
