### ISSUE TITLE
Use case for programmatic control of expanded state

### ISSUE THREAD

**Issue by GazEdBro** [springload/react-accessible-accordion#247]
We have form, split into several logical parts, which has a complete mess of co-dependant validations.  When a validation fails, we really need to expand the form to show the user what went wrong.  Before the normal howl of don't design like this, we are preparing the data for entry to a government system...
Good plugin though.  Regards Gary

**Comment by holloway** [comment]
Just co-opting this thread for another discussion of this, Hey @ryami333 .. what are your current thoughts on programmatic control? (I see #174 etc.).

I was thinking a bit more about this, and _if_ this feature had a niche use-case that's worth supporting then the API name could indicate that it's unsafe or dangerous... `dangerouslySetIsOpen` or similar to indicate that people are on their own if they want to control this, and to convey that it's not a feature that should be used casually.

**Comment by synecdokey** [comment]
This has been resolved in our latest release, version 3.1.0.

You will find `dangerouslySetExpanded` an an available prop on your `AccordionItem` as an escape hatch to set your expanded state manually.
