### ISSUE TITLE
Change ">" and move position

### ISSUE THREAD

**Issue by as703** [springload/react-accessible-accordion#248]
Hi all,

Is there a way to change the ">" icon in the accordionItemButton to a different icon? Also, can it's position be modified to be at the right-hand side of the item? Perhaps via CSS styling?

I've had a good look around the source code but can't find the reference to ">" icon.

Any pointers would be much appreciated.

Many thanks

**Comment by holloway** [comment]
Hi @as703

The `fancy-example.css` includes this style.

The ">" icon is a pseudo element styled in `.accordion__button:before` by making a box with 2 side borders and rotating it.

**Comment by as703** [comment]
Ah - I see. I was looking for a ">" and completely missed that it was constructed from a two sided box. I understand it now. Thank you very much.

**Comment by holloway** [comment]
Cheers :smile:

**Comment by as703** [comment]
I suppose to move it to the right of the text I can use the :after pseudo class. Not sure how to get the text far left and the "icon" far right though.

**Comment by as703** [comment]
Used "float:right" to sort it in the end. CSS here if anyone else is looking:

.accordion__button:after {
    float:right;
    line-height: 1;
    content: '';
    height: 10px;
    width: 10px;
    border-bottom: 2px solid currentColor;
    border-right: 2px solid currentColor;
    transform: rotate(-45deg);
}

.accordion__button[aria-expanded='true']::after,
.accordion__button[aria-selected='true']::after {
    transform: rotate(45deg);
}
