### ISSUE TITLE
How to use AccordionItemState?

### ISSUE THREAD

**Issue by paulgaumer** [springload/react-accessible-accordion#250]
Hi there,

I'd like to get access to the state info of my item but I can't seem to get `AccordionItemState` work. Could you please provide a simple example?

**Comment by paulgaumer** [comment]
Figured it out.
If you are in the same situation...

```
<AccordionItem>
    <AccordionItemHeading>
        <AccordionItemButton>
            <AccordionItemState>
                {(state) =>
                    `State: ${JSON.stringify(state)}`
                }
            </AccordionItemState>
        </AccordionItemButton>
    </AccordionItemHeading>
    <AccordionItemPanel>........</AccordionItemPanel>
</AccordionItem>
```

**Comment by ngphadke** [comment]
@paulgaumer - your example above helps render the state but that's not helpful for me. What I'm trying to execute is - 

```
<AccordionItemHeading>
            <AccordionItemButton>
                <div>
                           {expanded && <Icon />}
                </div>
            </AccordionItemButton>
        </AccordionItemHeading>
```

so how do I used `AccordionItemState` to provide the value of expanded in `{expanded && <Icon/>}` so that I can conditionally render my icon if the item is expanded

**Comment by ngphadke** [comment]
Figured it out. This finally helped me understand render-props.
Putting this down for anyone who would want to know how to use this particular one in a real example.

Say you want to show the title with a right-arrow icon when it is the one which is expanded then you can do that like so - 
```
<AccordionItemHeading>
            <AccordionItemButton className="outline-none">
                <div>
                        <span>
                            <AccordionItemState>
                                {(state) =>
                                    {
                                    return(
                                        state.expanded && <ArrowRight /> 
                                        )
                                    }
                                }
                            </AccordionItemState>
                        </span>
```
