### ISSUE TITLE
Use-case for programmatic control of expanded state

### ISSUE THREAD

**Issue by dwpramik** [springload/react-accessible-accordion#253]
I have a page that contains some visual data for our users based on some user selected parameters. The page contains charts and tables of the relevant returned data. After this visual data, there are sections representing the user selected filters and parameters that derived this data. 9/10 of the users will not care to see this data on a day to day basis, so we have the data hidden behind accordions that are collapsed by default. 

Users want the ability to save this page to PDF, or easily open up a print prompt for the page. In the function for this new button, I would like to expand these accordions for them so that when they print the page, the data within the accordion is shown, instead of just showing collapsed accordions, and without them having to scroll down, open the accordions, and then print the page.

**Comment by katie-day** [comment]
Thank you for your feedback, we'll look into this.
In the meantime could you use css and use a print media query, something like:

```
@media print {
    [hidden] {
         display: block !important;
    }
}
```

or 

```
@media print {
    .accordion__panel {
         display: block !important;
    }
}
```

**Comment by synecdokey** [comment]
A media query around the print use-case is the way to go, closing as a workaround has been provided.
