### ISSUE TITLE
[question] Accessibility Best-Practice, content inside of AccordionItemHeading

### ISSUE THREAD

**Issue by kutyepov** [springload/react-accessible-accordion#258]
Thank you for making this awesome library!

I will really appreciate if you could add some clarifications regarding the following line in the documentation:

> Only ever use phrasing content inside of your AccordionItemHeading component. If in doubt, use text only.

It is explained in #228 issue that AccordionItemHeading should not have any children except AccordionItemButton, however is it okay to have children inside of AccordionItemButton itself, such as:

```
<AccordionItem>
  <AccordionItemHeading>
    <AccordionItemButton>
      <h2>awesome title</h2> <---- is it ok to have h2 inside of AccordionItemButton?
      <svg>amazing svg icon</svg>
    </AccordionItemButton>
  </AccordionItemHeading>
  <AccordionItemPanel>
    <p>
      extraordinary text
    </p>
  </AccordionItemPanel>
</AccordionItem>
```

**Comment by holloway** [comment]
@kutyepov @thisKeeWord

My understanding is that `AccordionItemHeading` is a real heading (via `aria-role="heading"`) and headings inside other headings aren't allowed in HTML, so the `<h2>` isn't allowed.

I believe that nested `<button>`s, `<a>`, `<input>`, `<textarea>`, `<select>` etc would also not be ok.

SVGs would be fine though.

------------------------------------------------

We recently added a runtime check for guids that verifies that these ids are valid HTML5 Ids (per the spec, they must not contain ASCII whitespace). This only occurs during development, not on production builds.

We're considering whether it's possible to either:
1) constrain values for `AccordionItemButton` to only allow strings as values, or
2) give developer feedback on invalid tags, potentially at run-time, to raise these issues earlier.
