### ISSUE TITLE
TypeError: _this.expanded.filter is not a function when collapsing preExpanded item

### ISSUE THREAD

**Issue by joergreichert** [springload/react-accessible-accordion#259]
`
<Accordion allowMultipleExpanded={false} allowZeroExpanded={true} preExpanded={"A"}>
      <AccordionItem uuid={"A"}>
        ...
      </AccordionItem>
      <AccordionItem uuid={"B"}>
        ...
      </AccordionItem>
    </Accordion>
`
_this.expanded.filter in https://github.com/springload/react-accessible-accordion/blob/master/src/helpers/AccordionStore.ts#L57 is then only "A" leading to this _this.expanded.filter is not a function error, while when first expand and collapse "B" this is [ "B" ]. So this seems to be an issue with the combintion of allowZeroExpanded and preExpanded.

**Comment by joergreichert** [comment]
never mind, preExpanded={"A"} must be preExpanded={["A"]} , just read Readme.

**Comment by jmazier-j2d** [comment]
Thanks for giving the solution to your issue... I totaly missed that part in the doc, you saved me plenty of time 👍
