### ISSUE TITLE
Combination with react-router-use-location-state: back button not working

### ISSUE THREAD

**Issue by vicmortelmans** [springload/react-accessible-accordion#261]
Hi,

(note: while writing, I found out that this is probably NOT an issue; check below the code...)

I try to have an accordion linked to the browser history and URL query string, by combining with the [react-router-use-location-state](https://www.npmjs.com/package/react-router-use-location-state) package.

My component state = the value of my query field = the uuid of the open AccordionItem (I only allow one open).

I feed the current state to the `preExpanded` prop (as a list of a single element, or an empty list, if none is open).

I provide the `onChange` prop with a function that will set the state to the value of the uuid.

This works:

1.  the URL is updated correctly when I open/close an AccordionItem with the uuid of the open item (this means that the `onChange` is doing what it should do)
2. when I use the URL as a bookmark and open the app, the AccordionItem that is specified in the query string is opened (this means that the `preExpanded` is doing what it should do)

But the back button is not working.

When I click back, I can verify the the app is rendered and that the value for `preExpanded` is requested and provided correctly (= the uuid of the previously open AccordionItem). But the currently open AccordionItem is not closed and the requested AccordionItem is not opened.

What could possibly be going wrong?

Here's my code:

```
import React from 'react'; 
import { IonContent } from '@ionic/react';
import { Accordion, AccordionItem, AccordionItemHeading, AccordionItemButton, AccordionItemPanel, } from 'react-accessible-accordion';
import './Accordion.css';
import { useQueryState } from 'react-router-use-location-state';
import { slugify } from './Lib'
import structure from '../data/structure.json'
import './Home.css';

// auxiliary function to get and set navigation state
const setQueryState = (useQueryStateSetter: Function) => {
  return (accordionUuids: [string]) => {
    console.log("setQueryState: ");
    console.log(accordionUuids);
    useQueryStateSetter(accordionUuids.length ? accordionUuids[0] : '', { method: 'push' })
  }
}
const getQueryState = (queryState: string) => {
  console.log("getQueryState:");
  console.log(queryState ? [queryState] : [])
  return queryState ? [queryState] : [];
}

function Home () {

  const [openCategory, setOpenCategory] = useQueryState<string>('category', '');

  return (
    <IonContent>
      <header className='background-span'>{structure.title}</header> 
      {console.log("RENDERING with openCategory " + openCategory)}
      <Accordion 
        allowZeroExpanded={true} 
        className='category'
        preExpanded={getQueryState(openCategory)}
        onChange={setQueryState(setOpenCategory)}
        >
        {structure.categories.map((category) => (
          <AccordionItem uuid={slugify(category.title)} key={slugify(category.title)}>
            <AccordionItemHeading>
              <AccordionItemButton className='background-span accordion-button'>
                {category.title}
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel style={{padding: 0}}>
              <p>Open Category: {getQueryState(openCategory).toString()}</p>
            </AccordionItemPanel>
          </AccordionItem>
        ))}
      </Accordion>
    </IonContent>
  );
};

export default Home;
```

You can see that in the AccordionPanel, I display for debugging the same value that is provided to `preExapnded`. The displayed value changes as expected, but the accordion doesn't budge...

(oops)

OK, I've been writing my issue and reading and re-reading the README to see if I didn't miss anything and now I seem to understand that my "issue" is exactly what's described as "You may use the 'preExpanded' prop to set the initial expanded state, but it may not be controlled manually thereafter." Sorry, I didn't understand the 'manually controlling' part when first reading it.

I'm quite new to React, but one of the first things that I learned was that a component will re-render  when its props are modified. Isn't the `preExpanded` a prop of the <Accordion> component in this case? That's what confused me and made me automatically assume that whatever new in the prop would be rendered likewise.... unless stated otherwise, that is ;)

I suppose this ends my chances of having a back-button functionality? Or is there another way out?

Best regards,
Vic

**Comment by vicmortelmans** [comment]
Hi, 
Not pressing, just coming back to this, as I'm further developing my app, to note that I bumped into another blocked use case: providing a clickable link in one AccordionItem, that opens another AccordionItem.
Best regards,
Vic

**Comment by synecdokey** [comment]
Your instinct was right, preExpanded is only checked on the first render, as it would otherwise mess with the rest of the functionality around folding items automatically, I'd recommend using `dangerouslySetExpanded` for that use-case, with robust testing to ensure you are not messing with screen readers.

However, clickable links in an `AccordionItem` to open another one can't be supported without compromising on accessibility, I would not recommend a way around this. Hope that helps.
