### ISSUE TITLE
Error with first item expanded

### ISSUE THREAD

**Issue by tim-wgbh** [springload/react-accessible-accordion#264]
I've used the preExpanded attribute to open the first item.

If the user clicks on that item, an error is thrown.

![Screen Shot 2020-05-27 at 11 20 42 AM](https://user-images.githubusercontent.com/11877425/83039754-85057300-a00c-11ea-8e02-195da57f9ee7.jpg)

This breaks the page.

Is this a bug or am I not setting this up correctly?
This is the component:

`const ReasonsModule = () => (
  <>
    <a id="six-reasons" className="sixReasonsAnchor"></a>
    <div className="clearAll"></div>
    <div className="spacer"></div>

    <div className="wrapper">
      <h1 className="reasons">Six Reasons to Sponsor WGBH</h1>
      <div className="reasons-accordion">
        <Accordion allowZeroExpanded="true" preExpanded="item_1">
          <AccordionItem className="accordion_in" uuid="item_1">
            <AccordionItemHeading className="acc_head">
              <AccordionItemButton>
                  <div className="acc_icon_expand"></div><span>1</span> Increase your visibility before a large audience
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel className="acc_content">
              <img alt="" src={visibility} />
              <p className="reason_notes">TV – Nielsen NSI Live+7 Reach + Frequency Report Sept 2019, M–Su 3a–3a, P2+ &nbsp;|&nbsp; Radio - Scarborough Doublebase 8/17–8/19, M–Su 6a–12m, A18+ &nbsp;|&nbsp; Digital - Google Analytics Oct 2019 &nbsp;|&nbsp; Explore! Circulation Apr – Dec 2019</p>
            </AccordionItemPanel>
          </AccordionItem>

          <AccordionItem className="accordion_in" uuid="item_2">
            <AccordionItemHeading className="acc_head">
              <AccordionItemButton>
                  <div className="acc_icon_expand"></div><span>2</span> Associate your brand with America's most trusted institutions
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel className="acc_content">
              <img alt="NPR listeners take action in response to NPR messages" src={pbsTrust} style={{marginTop: "0px", marginBottom: "0px", width: "366px", height: "auto"}} />
              <div className="reason-section">
                <img alt="NPR listeners take action in response to NPR messages" src={nprTrust} style={{marginTop: "0px", marginBottom: "0px", width: "366px", height: "auto"}} />
              </div>v
              <p className="reason_notes">
                Source: PBS: Marketing & Research Resources, Inc. (M&RR) Jan 2019 &nbsp;|&nbsp; NPR: Lightspeed Research, NPR State of Sponsorship Survey, March 2019
              </p>
            </AccordionItemPanel>
          </AccordionItem>

          <AccordionItem className="accordion_in" uuid="item_3">
            <AccordionItemHeading className="acc_head">
              <AccordionItemButton>
                  <div className="acc_icon_expand"></div><span>3</span> Reach an educated, affluent, culturally-engaged audience
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel className="acc_content">
              <h2 className="television_sub" style={{textAlign: "center", color: "#133863"}}>Compared to the average Boston adult 18+, WGBH fans are:</h2>
              <p className="reason_notes"><img alt="" src={reach} style={{width: "1120px", height: "auto"}} /></p>
            </AccordionItemPanel>
          </AccordionItem>

          <AccordionItem className="accordion_in" uuid="item_4">
            <AccordionItemHeading className="acc_head">
              <AccordionItemButton>
                   <div className="acc_icon_expand"></div><span>4</span> Cover New England with television and radio
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel className="acc_content">
              <h2 className="television_sub" style={{textAlign: "center", color: "#133863"}}>WGBH's powerful signal reaches households across New England</h2>
              <p><img alt="WGBH Radio and Television Coverage Map" src={coverage} style={{width: "1120px", height: "auto"}} /></p>
            </AccordionItemPanel>
          </AccordionItem>

          <AccordionItem className="accordion_in" uuid="item_5">
            <AccordionItemHeading className="acc_head">
              <AccordionItemButton>
                   <div className="acc_icon_expand"></div><span>5</span> Enhance your corporate image and bottom line
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel className="acc_content">
              <h2 className="television_sub" style={{textAlign: "center", color: "#133863"}}>Sponsors benefit from public media's "halo effect"</h2>

              <div className="reason_section">
                <h1 className="reason_section_header fire_red">
                  <img alt="PBS viewers prefer to buy from PBS sponsors" src={pbsHalo} style={{marginTop: "0px", marginBottom: "0px", width: "366px", height: "auto"}} />
                </h1>
              </div>

              <div className="reason_section">
                <h1 className="reason_section_header violet">
                  <img alt="Public radio listeners take action in response to something heard on NPR" src={nprHalo} style={{marginTop: "0px", marginBottom: "0px", width: "370px", height: "auto"}} />
                </h1>
              </div>

              <p className="reason_notes">Source: PBS: Lightspeed Research/SGPTV Viewer Attitudes & Behaviors Study, March 2018 &nbsp;|&nbsp; NPR: Lightspeed Research, NPR State of Sponsorship Survey, March 2019</p>
            </AccordionItemPanel>
          </AccordionItem>

          <AccordionItem className="accordion_in" uuid="item_6">
            <AccordionItemHeading className="acc_head">
              <AccordionItemButton>
                   <div className="acc_icon_expand"></div><span>6</span> Break through the media clutter
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel className="acc_content">
                      <h2 className="television_sub" style={{textAlign: "center", color: "#133863"}}>With far fewer minutes than commercial broadcast, WGBH sponsor spots stand out</h2>
              <div className="reason_section"><img alt="" src={breakthroughTV} style={{width: "396px", height: "auto"}} /></div>

              <p className="reason_section"><img alt="" src={breakthroughRadio} style={{width: "396px", height: "auto"}} /></p>

              <p>&nbsp;</p>

              <p className="reason_notes">Source: Television:&nbsp;<em>Frontline</em>&nbsp;2/20/18 &nbsp;|&nbsp; <em>60 Minutes</em> on WBZ TV Boston,&nbsp;3/4/18 &nbsp;|&nbsp; Radio: 89.7 WGBH&nbsp;<em>Morning Edition</em>, 3/26/18, 9a–10a &nbsp;|&nbsp; WBZ-AM 1030 Boston 4/18/ 7a–8a</p>
            </AccordionItemPanel>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  </>
)
`

**Comment by holloway** [comment]
I think `preExpanded` should take an array, not a single value. ie,  `preExpanded={["item_1"]}`

**Comment by holloway** [comment]
@tim-wgbh  Any update? I'll close this in a few days if I haven't heard from you - thanks

**Comment by franky-chanyau** [comment]
can confirm that supplying an array to `preExpanded` resolved a similar issue on my end. Chur for the component and straightforward API, would love to link up and show you how I've integrated it into my current project

**Comment by katie-day** [comment]
Closing this issue but please reopen if you need to discuss further
