### ISSUE TITLE
Accordion expands on space

### ISSUE THREAD

**Issue by Mujaddadi** [springload/react-accessible-accordion#267]
Hi, I have a requirement to open a modal, containing some form, when user click on an icon in the modal header. The problem is that when user enter space in a textfield element of form, instead of registering the space, accordion open and close. I am not sure what is the best way to deselect the accordion. I have tried all kind of stuff preventDefault, stopPropagation and try to capture the space key event. What's the best way to address it?

**Comment by Mujaddadi** [comment]
The culprit is this code in AccordionItemButton
```
if (keyCode === keycodes.ENTER || keyCode === keycodes.SPACE) {
            evt.preventDefault();
            this.props.toggleExpanded();
  }
```

It will be good if there is a way to disable onKeyPress event. I don't think there is any real important for this in terms of accessibility.

**Comment by Mujaddadi** [comment]
Anyway I fixed the issue by moving modal out of the accordion header. Not an idea solution but it worked. Still it will be good to have the option to disable onKeyPress event.

**Comment by bulby97** [comment]
@Mujaddadi  Can you give me a codepen example ? I want to be sure it's a required feature before working on it :). Thanks !

**Comment by holloway** [comment]
Closing this due to a lack of response, but please feel free to reopen it if you wish to discuss further :smile:

**Comment by Mujaddadi** [comment]
Sorry I forgot to create the sandbox. Here is the example. 

https://codesandbox.io/s/patient-snow-6vbrw?file=/src/MyAccordion/index.js

If you press enter or space in textarea of modal, it will expand and close the accordion. In latest version of react-accessible-accordion, it only happens when we pass allowZeroExpanded props to Accordion component.

**Comment by synecdokey** [comment]
Hello,

So the problem here is that your Modal is *inside* the accordion, and the keydown event will propagate up to it and will be caught by the Accordion as a result. There are two ways to make it work:
- Put the modal outside of the Accordion
- use `onKeyDown={(ev) => {ev.stopPropagation()}}` on your `textarea`

**Comment by Mujaddadi** [comment]
Well, if you look at my previous comments, that what I mentioned. I solved it by moving the modal outside the Accordion header. But it's not the best solution, since  hierarchically it belongs in the header. I tried the stopPropogation also but it didn't stop the event from bubbling up to the header.
