### ISSUE TITLE
linking to a specific AccordionItem

### ISSUE THREAD

**Issue by birthdaycorp** [springload/react-accessible-accordion#270]
Is it possible to link to an AccordionItem so that it is expanded when the page loads?

**Comment by holloway** [comment]
Give the `AccordionItem` a uuid and that will be attached to the `AccordionButton` as an id. Eg. https://react-accessible-accordion.springload.co.nz/#accordion__heading-0

and then you could use `preExpanded` to expand that same item

**Comment by holloway** [comment]
Assuming this is addressed. Reopen if you want to discuss further
