### ISSUE TITLE
preExpanded doesn't work

### ISSUE THREAD

**Issue by iozzyi** [springload/react-accessible-accordion#278]
even on the demo page: https://react-accessible-accordion.springload.co.nz/

you can inspect the attributes, the Pre-Expanded example Accordion has the attribute `preExpanded=[$uuid1]` where $uuid1 is the UUID of the first AccordionItem, but the Provider of the first AccordionItem has the prop `expanded={false}`, and you can see visually that the first AccordionItem is not pre-expanded.

Visual on page load:
![image](https://user-images.githubusercontent.com/6170289/87036586-f37c4a00-c1e2-11ea-8245-399535f252e4.png)

First item UUID:
![image](https://user-images.githubusercontent.com/6170289/87036661-13ac0900-c1e3-11ea-8fff-da2683c610bf.png)

Accordion preExpanded value:
![image](https://user-images.githubusercontent.com/6170289/87036766-38a07c00-c1e3-11ea-989f-d6c1a88d68f4.png)

**Comment by liamjohnston** [comment]
@iozzyi Thanks for this. 

I'm not sure why the demo was broken, but my latest (unrelated) update to add code examples to the demo seems to have fixed it. 

Let me know if you still see this issue. Cheers!

**Comment by iozzyi** [comment]
@liamjohnston Thanks, I can see it has now been fixed.

But the tag v3.3.0 is still pointing to the previous commit. Does the demo page use the latest commit even though it says v3.3.0?

Could you make a tag, say 3.3.1 for the update so I can update my project?

Thanks

**Comment by ngphadke** [comment]
Same as @iozzyi .... the `preExpanded` is not working. Confirmed by checking the `expanded` state of the item that should have been expanded

**Comment by holloway** [comment]
@iozzyi I've released version 3.3.1. Does that work for you?

![Screenshot from 2020-07-21 10-47-27](https://user-images.githubusercontent.com/620580/87993866-b77ca980-cb3f-11ea-85dc-dcbc637304b1.png)

**Comment by iozzyi** [comment]
Yes, thank you!
