### ISSUE TITLE
allowMultipleExpanded is not working

### ISSUE THREAD

**Issue by mayank-abhijeet-kr** [springload/react-accessible-accordion#281]
When i write allowMultipleExpanded={false} (which is also the default value), still i am able to expand multiple accordions.

<div>
{allDomains.map((domain) => {
          const { id, mobileBackground, domainName, mentors } =
            mentorsInDomains[domain] || {};
          return (
            <Accordion key={id} allowZeroExpanded={true} allowMultipleExpanded={false} >
              <AccordionItem uuid={id} >

                <AccordionItemHeading>
                  <AccordionItemButton>
                    <div className="font-medium font-pink">{domainName}</div>
                  </AccordionItemButton>
                </AccordionItemHeading>

                <AccordionItemPanel>
                  <div>some message</div>
                </AccordionItemPanel>

              </AccordionItem>
            </Accordion>
          );
        })}
</div>

**Comment by liamjohnston** [comment]
@mayank-abhijeet-kr You've said that `allowMultipleExpanded` "is also the default value". That is not the case.

Try adding the `allowMultipleExpanded` to your `<Accordion>` component.

Let me know if that still does not work :)

**Comment by mayank-abhijeet-kr** [comment]
@liamjohnston Even when i pass prop allowMultipleExpanded={false}, I am able to open multiple accordions.

**Comment by holloway** [comment]
@mayank-abhijeet-kr I can reproduce the bug on our demo page, can you? https://react-accessible-accordion.springload.co.nz/

**Comment by holloway** [comment]
bump

**Comment by willholland** [comment]
I have a similar issue.

I'm using Redux to manage the state of allowMultipleExpanded and allow allowZeroExpaned. 

I can toggle both options from true to false. I can see that the values are being updated and the component is re-rendering, but the functionality available on the page is still acting like both values are true. 

It's not until I refresh the page that the new settings take effect.

**Comment by katie-day** [comment]
@mayank-abhijeet-kr I can't see your full example as I don't think you have copy and pasted the whole thing but what it looks like to me is that you may be `mapping` over the whole `accordion` rather than just the accordion `item`'s which would mean every `item` is inside an individual `accordion`. 

```
<Accordion>
            { data.map( item => (
                <AccordionItem key={item.heading}>
                    <AccordionItemHeading>
                        <AccordionItemButton>
                            {item.heading}
                        </AccordionItemButton>
                    </AccordionItemHeading>
                    <AccordionItemPanel>{item.panel}</AccordionItemPanel>
                </AccordionItem>
            ))}
</Accordion> 
```

**Comment by ashish-mesvaniya** [comment]
> @mayank-abhijeet-kr You've said that `allowMultipleExpanded` "is also the default value". That is not the case.
> 
> Try adding the `allowMultipleExpanded` to your `<Accordion>` component.
> 
> Let me know if that still does not work :)

when i use this my screen goes all white, means my webpage goes all white
