### ISSUE TITLE
Checkbox in heading click not working properly

### ISSUE THREAD

**Issue by pradeepvish1213** [springload/react-accessible-accordion#283]
![image](https://user-images.githubusercontent.com/11312956/88473818-40546600-ceef-11ea-8914-4f92e3f6b162.png)

I have issue with some systems not all browsers and all systems.
When I create a checkbox in heading and another checkbox in pannel. See the above screenshot.
when I click any checkbox accordion going to close and also checkbox checked.
Can you please help me out with this issue.

**Comment by holloway** [comment]
Hi @pradeepvish1213 

Accordion Headings should only have "phrasing content" see https://github.com/springload/react-accessible-accordion#accessibility-best-practice

**Comment by pradeepvish1213** [comment]
Hi @holloway 

Thanks for your reply. I am really happy with your word. 
When I debug code with the onChange event I found every time UUID change.
Then I set UUID fixed value then solved.

finally solved.

thanks.

**Comment by holloway** [comment]
@pradeepvish1213 Ah, that was a recent bug. Upgrade to version 3.3.3 and you won't need to set the UUID
