### ISSUE TITLE
How to stop reset accordion items when i change locale state in this component?

### ISSUE THREAD

**Issue by AkhmerovM** [springload/react-accessible-accordion#284]
Hello everyone, i found a problem, that when i called useState hook, all accordion items has closed. 
may be exists key for items, then will not close items when component rerender?

**Comment by ge022** [comment]
Same issue here, and it is occurring since version 3.3.0

**Comment by holloway** [comment]
Hi, I'll look at this bug this week.

**Comment by InfraK** [comment]
The issue goes away if you add `uuid` to the `AccordionItem`, the key prop used to do the same, but must have changed the behavior in recent versions.

**Comment by holloway** [comment]
@InfraK ah thanks for looking into that. I'd started but couldn't reproduce the bug yet.

**Comment by holloway** [comment]
https://github.com/springload/react-accessible-accordion/pull/285

**Comment by holloway** [comment]
Release v3.3.3 ... can you see if this fixes the issue for you @InfraK @ge022 @AkhmerovM ?

**Comment by InfraK** [comment]
Can confirm is working now @holloway thank you.

**Comment by holloway** [comment]
Assuming fixed. Please reopen if you're still having problems.
