### ISSUE TITLE
Accordion collapses on changing component's state

### ISSUE THREAD

**Issue by msspl-subhom-kundu** [springload/react-accessible-accordion#289]
In my case, I have multiple checkboxes in each accordion which does state update. And If I click any one of the checkboxes, accordion collapses automatically due to the re-render of the component. please help

**Comment by holloway** [comment]
@msspl-subhom-kundu Which version are you using? Are you using the latest one?

**Comment by msspl-subhom-kundu** [comment]
yes, solved the issue, forgot to include uuid={index} inside .map()
