### ISSUE TITLE
Pass in elements as children to AccordionItemButton

### ISSUE THREAD

**Issue by thisKeeWord** [springload/react-accessible-accordion#290]
Could we allow rendering html elements inside the AccordionItemButton as children? With the project I'm working on, I need to use an Icon component that renders icons along with text. However, the AccordionItemButton can only display what's passed in using dangerouslySetInnerHTML or text.

Is it possible to have something like this 
```
<AccordionItemButton>
   <div> something <some image element> </div>
</AccordionItemButton>
```

rather than 
```
<AccordionItemButton
   dangerouslySetInnerHTML={{
      __html: `<div> something  <some image element> </div>
   }}></AccordionItemButton>
```
?

The use of dangerouslySetInnerHTML is a known bad practice and poses XSS attacks: 
> In general, setting HTML from code is risky because it’s easy to inadvertently expose your users to a cross-site scripting (XSS) attack. So, you can set HTML directly from React, but you have to type out dangerouslySetInnerHTML and pass an object with a __html key, to remind yourself that it’s dangerous.

**Comment by angelocordon** [comment]
Yes, this is possible.

**Comment by GeorgeWL** [comment]
>AccordionItemButton can only display what's passed in using dangerouslySetInnerHTML or text.

**Comment by irhamputra** [comment]
@thisKeeWord yes I agree that dangerouslySetInnerHTML is bad practice. if you want to do so, you need to sanitze it first before rendering the html in dangerouslySetInnerHTML
maybe this could help you https://stackoverflow.com/questions/38663751/how-to-safely-render-html-in-react

**Comment by GeorgeWL** [comment]
But React allows the passing of Children as a property, so there's even less reason it should be using it.

**Comment by thisKeeWord** [comment]
@GeorgeWL I'm pretty sure I tried that already and couldn't find a solid working solution. However, this is an old question so I'll close it for now and reopen if need be.
