### ISSUE TITLE
Orientation of accordion

### ISSUE THREAD

**Issue by pradeepvish1213** [springload/react-accessible-accordion#295]
I need to add a vertical accordion. Please add an orientation feature.

**Comment by liamjohnston** [comment]
In the absence of an actual orientation option to allow this, it could be achieved with CSS.

Simply adding `display: flex;` to `.accordion__item` would result in something like this:
![Screen Shot 2021-04-13 at 8 41 40 AM](https://user-images.githubusercontent.com/1134713/114459143-3f599500-9c34-11eb-9136-aee5b4b02f2f.png)
(you'd need to fine tune this, but you get the idea)

Please forgive my ignorance - is this to support some non-western (ltr) reading style, or is it just for something specific to your UI?

**Comment by holloway** [comment]
Assuming this is dealt with. Please reopen if there is any issue.
