### ISSUE TITLE
Props not updating in AccordionItemPanel after opening

### ISSUE THREAD

**Issue by helrond** [springload/react-accessible-accordion#296]
I'm experiencing unexpected behavior when trying to load data into an AccordionItemPanel. It seems that changes to props do not update the AccordionItemPanel once is has been opened.

I am recursively nesting accordions, and fetching data for each accordion as I go. Accordion items are passed to each Accordion as props from the parent node. Data is being fetched from a paged endpoint and saved to the parent node's state. I want to open the panel immediately and load data as it is returned from each page.

What's happening instead is that the first page (sometimes two, depending on the speed of the response) shows up when the accordion is open, but once the accordion opens, even though props are still updating (which I've confirmed by logging out the state changes in the parent component) those changes aren't reflected in the nested accordion. I've successfully been able to load changing props in other elements (a plain div, for example) so this seems to be specific to either the AccordionItemPanel component or one of its parents.

Is this expected behavior, or is there something I can do so that changed props are always reflected, regardless of whether the accordion is open or not?

Here's a simplified version of my components:
```
class RecordsChild extends Component {
  constructor(props) {
    super(props)
    this.state = {
      children: [],
    }
  }

  childList = children => {
    const { ariaLevel, parent, params, savedList, setActiveRecords, toggleInList } = this.props;
    return (
      children.map(child => (
        <RecordsChild
          item={child} />
        )
      )
    )
  }

  getChildrenPage = uri => {
    axios
      .get(uri)
      .then(res => {
        this.setState({ children: [...this.state.children].concat(res.data.results)})
        res.data.next && this.getChildrenPage(res.data.next)
      })
      .catch(e => console.log(e))
  }

  handleCollectionClick = uri => {
    if (!this.state.children.length) {
      this.getChildrenPage(uri)
    }
  }

  render() {
    const { item } = this.props;
    return (<AccordionItem
        uuid={item.uri} >
        <AccordionItemHeading
          onClick={() => this.handleCollectionClick(item.uri)} >
          <AccordionItemButton>
            {item.title}
          </AccordionItemButton>
        </AccordionItemHeading>
        {(this.state.children) ?
        (<AccordionItemPanel>
          <Accordion >
            {this.childList(this.state.children)}
          </Accordion>
        </AccordionItemPanel>) :
        (null)}
      </AccordionItem>
      )
    )
  }
}

const RecordsContent = props => {
  const childList = children => {
    return (
      children.map(child => (
        <RecordsChild
          key={child.uri}
          item={child} />
        )
      )
    )
  }
  return (
      <Accordion>
        {childList(props.children)}
      </Accordion>
)}
```

**Comment by irhamputra** [comment]
@helrond I assume this component can't handle the async process. My idea for this solution, I think you need to render all async process first and then after finish you can render the component for sync interacting

**Comment by helrond** [comment]
Thanks @irhamputra - I ended up writing my own Accordion component to resolve this issue.

**Comment by holloway** [comment]
As reported in #305 there may have been a bug fixed in a recent release. As you've solved this issue by using a different accordion I'll consider this fixed for now. Please reopen if there's a remaining issue.
