### ISSUE TITLE
Clicking Input located on AccordionItemButton

### ISSUE THREAD

**Issue by shushan-ab** [springload/react-accessible-accordion#299]
How can I override event during expanding or collapsing, when I'm clicking on input located on AccordionItemButton?

**Comment by holloway** [comment]
My understanding is that you're not supposed to do that to maintain accessibility.

**Comment by shushan-ab** [comment]
Thanks for answer @holloway!
By the way I have added custom checkbox and it worked without any additional changes, so by clicking checkbox AccordionPanel didn't collapse.Then I thought that it should be working with input(type=number) as well.

**Comment by katie-day** [comment]
I'm just closing this ticket for now, but please reopen to discuss further
