### ISSUE TITLE
Replace placeholder Lorem Ipsum with real-world content in the demo

### ISSUE THREAD

**Issue by thibaudcolas** [springload/react-accessible-accordion#3]
Springload has a "no lorem ipsum" policy. While I wouldn't mind a quick dose of lorem in development, for the online demo it's a missed opportunity to make the accordions look more realistic by using real-world content.

I would suggest replacing the lorem with descriptions on how to use the accordion ("eat your own dog food"), potentially with code snippets powered by [Prism.js](http://prismjs.com/).

Edit: here is a very basic example

<img width="648" alt="react-accessible-accordion" src="https://cloud.githubusercontent.com/assets/877585/25584341/48af86b2-2e9e-11e7-9d76-168d7180c9d8.png">

**Comment by vincentaudebert** [comment]
Fixed by commit above.

**Comment by thibaudcolas** [comment]
Looks much better already!
