### ISSUE TITLE
Thoughts on https://www.w3.org/TR/wai-aria-practices/#accordion

### ISSUE THREAD

**Issue by pudgereyem** [springload/react-accessible-accordion#30]
Hey!

I'm creating a accordion component myself, and during the research I looked at the *WAI-ARIA Authoring Practices 1.1* which contains a section about [Accordion](https://www.w3.org/TR/wai-aria-practices/#accordion) together with an [example](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html).

I just wanted to check with you guys, if you had read it, and if so, what you think about it.

Cheers

---

> EDIT 2017-10-11: Added links.

**Comment by ryami333** [comment]
@pudgereyem your query is quite open-ended - would you be able to give a little bit of context or perhaps let us know what, specifically, you'd like us to comment on? This is the reference material against which I built `react-accessible-tooltip`, and though I've only joined `react-accessible-accordion` relatively recently, I highly suspect it was the source material used here too.

**Comment by vincentaudebert** [comment]
Hi @pudgereyem 

It was quite a while ago but indeed, it looks like we were highly influenced by the source repos we used to build this one. Both are using `tab` and we didn't really question this.
I made the changes here (https://github.com/springload/react-accessible-accordion/pull/32) to follow the ARIA for accordion. Please feel free to comment & give any feedback.

Thanks.

**Comment by pudgereyem** [comment]
@vincentaudebert @ryami333 awesome. If I get time later I can check out the changes in https://github.com/springload/react-accessible-accordion/pull/32. However, I'm not a user of this repo (as of now). Just wanted to tell you.

Cheers!

**Comment by vincentaudebert** [comment]
No worries I think I will merge it at some point soon as it makes more sense ARIA wise. But just looking for a second opinion. 

@ryami333 or @samanthaksanders feel free to jump in too for the review.

**Comment by samanthaksanders** [comment]
I take it we're using simple div's and applying roles and level so that there are no associated styles people will need to apply? If it were me I'd consider using native host language elements like headings and buttons so you wouldn't need to apply these roles and levels. Food for thought anyway.

I also presume we have only made the role region change for the strict accordion option not the multi collapse right?
```
Avoid using the region role in circumstances that create landmark region proliferation, e.g., in an accordion that contains more than approximately 6 panels that can be expanded at the same time.
```

**Comment by ryami333** [comment]
Are there any actionables here, or can this issue be closed?

**Comment by vincentaudebert** [comment]
@ryami333 I'll give it more thoughts asap once the new version is out.

**Comment by samanthaksanders** [comment]
Yes we should probably scrap #32 and redo it since we've just released a new version with a lot of updates. Let's move from tab related attributes to the accordion.

For reference here is tab related approach:
https://www.w3.org/TR/wai-aria-practices/#tabpanel

And the probably preferred accordion approach:
https://www.w3.org/TR/wai-aria-practices/#accordion

**Comment by ryami333** [comment]
Thinking big picture here - would it make more sense to actually split this into two different packages (or atleast two different _sets_ of components) - one for the Accordion approach and one for the Tab approach? I think it would be a tidier implementation than the conditional-based approach we have at the moment.

**Comment by vincentaudebert** [comment]
We could @ryami333 
Although it looks like supporting both in one package is the "normal" behaviour for most (all?) of the other similar packages and users might expect the same from RAA.

**Comment by ryami333** [comment]
So we might need to split into multiple component sets then, eg.
- `Accordion`, `AccordionItem`, `AccordionItemTitle`, `AccordionItemBody`.
- `TabPanel`, `TabPanelItem`, `TabPanelItemTitle`, `TabPanelItemBody`.

Otherwise, as I mentioned above, this is just going to get too hard to maintain.

**Comment by vincentaudebert** [comment]
I would agree to something like that. 
Let's get the aria changed first then we can investigate the full keyboard support and split if it's really necessary? Or you reckon it could be worth to split right now and have clearer maintenance/improvements later on?

**Comment by ryami333** [comment]
Nah fixing the aria first makes sense to me, then we'll work out the next steps.

**Comment by teemopower** [comment]
Hi guys, is this still being worked on?

**Comment by ryami333** [comment]
Heya @teemopower, are you asking if the project is still being worked on, or about this issue specifically? There's not really any actionables here as AFAIK, just some discussion about future direction and priorities.

**Comment by TomCrowley** [comment]
Is this on the roadmap? role="tab" is not proper support for accordion interactions. We are going to have to drop this package because it won't pass Aria certification. The current implementaiton gives the incorrect interaction and won't behave as expected for screen readers.

**Comment by ryami333** [comment]
@TomCrowley could you please give some context for this comment? What gave you the impression that the extent of our accessibility functionality was adding `role="tab"`?

**Comment by TomCrowley** [comment]
We had the component in production evaluated by Level Access and accessibility certification firm. It failed because of the inappropriate role="tab" and role="tabpanel" attributes on the accordion headers and panels respectively. I wasn't meaning to imply that the only accessibility consideration just that it was incorrect according to the guidelines. https://www.w3.org/TR/wai-aria-practices/#accordion

**Comment by ryami333** [comment]
@TomCrowley we would be very interested in seeing that report :) We do have a major release upcoming, and an internal accessibility review is underway as part of that release. As an example of an issue which I've already identified, see this line: https://github.com/springload/react-accessible-accordion/blob/6a7ebf527682e323557e3c817b95de37721ce616/src/AccordionItemTitle/AccordionItemTitle.tsx#L47

That ternary looks to me like it's the wrong way around. For a strict 'accordion' the role should be `button`, as you've pointed out.

**Comment by ryami333** [comment]
Spec compliance issues have all been resolved (and strictly browser-tested!) in the upcoming v3.0.0 release. Track progress of that release [here](https://github.com/springload/react-accessible-accordion/issues/168) and [here](https://github.com/springload/react-accessible-accordion/pull/188) 🍾
