### ISSUE TITLE
AccordionItem contents do not update unless they are toggled or the containing Accordion is rerendered

### ISSUE THREAD

**Issue by cmbartschat** [springload/react-accessible-accordion#305]
Demo of the behavior I'm seeing here:
~~https://codesandbox.io/s/fast-fog-c97v~~ New link: https://codesandbox.io/s/react-accordion-issue-c97v1

The expected behavior is that the contents of the heading and panels update when the count is incremented, but they only refresh when they are toggled.

Please let me know if I can provide any additional details.

**Comment by ushamacdonald** [comment]
@cmbartschat Could you check the access on that sandbox? That link doesn't work currently.

**Comment by cmbartschat** [comment]
@ushamacdonald should be back now, I guess I had to re-login for the link to work again, viewing in incognito is working for me now.

**Comment by cmbartschat** [comment]
There's also this link to just the displayed project, maybe this is more permanent? https://c97v1.csb.app/

**Comment by holloway** [comment]
@cmbartschat That codesandbox link is still 404ing for me, even in incognito

**Comment by cmbartschat** [comment]
How about https://codesandbox.io/s/react-accordion-issue-c97v1?

**Comment by ushamacdonald** [comment]
@cmbartschat Great that works now :+1:

**Comment by ushamacdonald** [comment]
@cmbartschat Upgrading to the latest release of RAA fixes this bug for me - on a forked version of your example. Does this work for you?

**Comment by cmbartschat** [comment]
Yes, I'm seeing that it works as expected on the latest. Comparing the [v3.3.3 tag to master](https://github.com/springload/react-accessible-accordion/compare/v3.3.3..master), maybe switching from class components to function components fixed the issue as a side effect? Otherwise I'm not really sure what to think.

**Comment by holloway** [comment]
Fixed
