### ISSUE TITLE
feature request: option to animate height during accordion transition

### ISSUE THREAD

**Issue by blord-fullscreen** [springload/react-accessible-accordion#31]
This seems pretty fundamental to the whole idea of "accordion". I was surprised animation isn't part of this.

You might want to take a look at this, which gives you both callbacks and classes:

https://github.com/faceyspacey/animated-transition-group

**Comment by ryami333** [comment]
I'll discuss this later with @vincentaudebert, but I would be pretty confident in saying that baking in animation would reach far outside the scope of this project.

Having said that, it's already quite simple to roll your own animations in combination with this package - you can trigger CSS transitions using the `hideBodyClassName` properties, or trigger `Web Animation`s using the `onChange` callbacks 😃 

If I can some time I might be able to write you a JS-Fiddle or two, and we might be able to update the README with those examples.

**Comment by blord-fullscreen** [comment]
> it's already quite simple to roll your own animations in combination with this package - you can trigger CSS transitions using the hideBodyClassName properties

Hah. Pure CSS class transitions don't work for accordion contents of variable or unknown height. You have to measure the height of the contents at the time of the 'open' events, then set the height style inline. But you also have to allow contents to reflow (based on resize, etc) once the accordion has expanded. So the inline style has to be removed after transition complete. `transitionend` events fire inconsistently, so that's tricky. These problems that have not yet been perfectly solved in the React space. (FWIW jQuery plugins historically spent years fine tuning and perfecting this.) If you don't want to take this on, I totally understand. It's harder than "quite simple".

> or trigger Web Animations using the onChange callbacks 😃

Web Animations aren't supported in Safari or Edge.

A show/hide toggle switch is not an "accordion". This isn't a quibble. Look at the thousands of accordion modules out there. None of them work like yours. The name is misleading.

**Comment by ryami333** [comment]
@blord-fullscreen are you aware that an 'accordion' is a concept of accessibility that can be appropriated as per W3's [Aria Spec](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html)? Authoring an accordion to that spec is not trivial, as it requires a very specific markup, combinations of aria attributes, and specific responses to specific keypresses. This package simply aims to alleviate those complexities while building such a component, _so that you only have to worry about the styling_. Jquery has not monopolized the name 'Accordion' with its gaudy and janky transitions, but it probably _could_ be used in conjunction with this project to solve the problem that you are trying to solve, in an accessible manner.

Thanks for your comments - if nothing else they might have revealed a gap in our documentation where we could be more explicit about the scope of this package, but animations are almost certainly outside of those, and I feel the name of this package perfectly summarises what it is and does. If you feel you've a better name, please raise another issue (or even better - a PR!) and we'll address that separately 😃 

Take care!
