### ISSUE TITLE
onChange of input element inside AccordionItemPanel is not fired

### ISSUE THREAD

**Issue by beulahpt** [springload/react-accessible-accordion#310]
I have defined an input inside AccordionItemPanel. I need to store this value onChange. Unfortunately input's onChange is not at all called. Any specific reason?

**Comment by ushamacdonald** [comment]
@beulahpt Do you have a code example I could look at?

**Comment by beulahpt** [comment]
@ushamacdonald it works now. It's because of a typo. My mistake only.
