### ISSUE TITLE
Cannot use 0 as a UUID

### ISSUE THREAD

**Issue by gavinhenderson** [springload/react-accessible-accordion#324]
When you pass 0 as the UUID to `AccoridanItem` it gets ignored.

An example of this causing an issue:

```jsx
<Accordion
  onChange={(selectedItems) => setSelected(selectedItems)}
  allowMultipleExpanded
  allowZeroExpanded
>
  {faqs.map((faq, index) => (
    <AccordionItem uuid={index} key={faq.question}>
      <AccordionItemHeading aria-level="3">
        <AccordionItemButton className={styles.faqQuestion}>
          <Avatar className={styles.avatar}>
            {selected.includes(index) ? (
              <KeyboardArrowDownIcon className={styles.icon} />
            ) : (
              <ChevronRightIcon className={styles.icon} />
            )}
          </Avatar>
          {faq.question}
        </AccordionItemButton>
      </AccordionItemHeading>
      <AccordionItemPanel>
        <div
          className={styles.faqAnswer}
          dangerouslySetInnerHTML={{ __html: faq.answer }}
        ></div>
      </AccordionItemPanel>
    </AccordionItem>
  ))}
</Accordion>
```

In the above example for the first element `faqs` will pass 0 to `AccordianItem` but then it gets ignored and the UUID is set to the default RAA one. This then causes the chevron later on not to get flipped. 

[This looks like the problematic line of code](https://github.com/springload/react-accessible-accordion/blob/e0dc05b7f12f3881d56308767890870e4cc71aea/src/components/AccordionItem.tsx#L27
). Due to 0 being falsy it uses `instanceUuid`. Maybe it should not do a falsy check but a more explicit `undefined` and `null` check?

**Comment by gavinhenderson** [comment]
My temporary fix is to use `index + 1` rather than `index` but the ideal fix for me would be an explicit undefined and null check

**Comment by holloway** [comment]
I agree. That deffo sounds like a bug
