### ISSUE TITLE
[BUG] AccordionItemPanel does not have role at all

### ISSUE THREAD

**Issue by DraikoNick** [springload/react-accessible-accordion#327]
React Accessible Accordion documentation says that it applies appropriate role attributes (button, heading, region).
But sometimes this action does not work properly.
For example there are an examples from React Accessible Accordion examples:
1. example with existing role (region) in the AccordionItemPanel: [click to check example of the highlighted title](https://react-accessible-accordion.springload.co.nz/#:~:text=spec%20for%20accessibility.-,Default%20behaviour,-By%20default%2C%20only)
`<div data-accordion-component="AccordionItemPanel" class="accordion__panel" role="region" aria-labelledby="accordion__heading-raa-0" id="accordion__panel-raa-0">In pariatur <a href="#">excepteur</a> ut do aliquip qui mollit aliqua exercitation <a href="#">excepteur</a> consequat reprehenderit nostrud laborum voluptate veniam non dolore dolore aliqua incididunt amet nisi minim cillum elit.</div>`

2. example without any role of the AccordionItemPanel: [click to check example of the highlighted title](https://react-accessible-accordion.springload.co.nz/#:~:text=Expanding%20multiple%20items%20at%20once)
`<div data-accordion-component="AccordionItemPanel" class="accordion__panel" aria-hidden="false" aria-labelledby="accordion__heading-raa-6" id="accordion__panel-raa-6">In pariatur <a href="#">excepteur</a> ut do aliquip qui mollit aliqua exercitation <a href="#">excepteur</a> consequat reprehenderit nostrud laborum voluptate veniam non dolore dolore aliqua incididunt amet nisi minim cillum elit.</div>`

There is explanation from axeDevTools: [axe.deque.com](https://axe.deque.com/issues/60a7fd8d-f073-444a-b3fc-03e2389d233c)

**Comment by holloway** [comment]
Good catch, I'll look at this today.

**Comment by holloway** [comment]
@DraikoNick it seems the `role="region"` logic is based on `allowMultipleExpanded`,

https://github.com/springload/react-accessible-accordion/blob/main/src/helpers/AccordionStore.ts#L91

I'll ask the previous developers what the justification for this is, but I'd guess that it's based on [this Aria advice](https://w3c.github.io/aria-practices/#accordion),

> Optionally, each element that serves as a container for panel content has role region and `aria-labelledby` with a value that refers to the button that controls display of the panel.
> * Avoid using the region role in circumstances that create landmark region proliferation, e.g., in an accordion that contains more than approximately 6 panels that can be expanded at the same time.
> * Role region is especially helpful to the perception of structure by screen reader users when panels contain heading elements or a nested accordion.

Although "Optional" the omission of `role="region"` in RAA is for accordions with multiple panels, not just 6+ panels, so I think there's a good justification for changing this behaviour in RAA to better adhere to this advice.

"approximately 6 panels that **can** be expanded" so there's a question of how fuzzy the "approximately 6" is (exactly 6 or not?), and whether we should vary behaviour based on the number of panels exceeding "approximately 6".

I think RAA should apply the region regardless, but I'll consult with others before making this change.

**Comment by CalinDale** [comment]
Whether or not the accordion panels should have region roles is dependant on the content in them. If it is significant content, like an entire section of the page, then it should have a region role. If it is something minor like some extra info on a subject, then it should not have a region role and can just be a <div>.

The AXE issue being picked up is that `<div>` elements don't support `aria-labeldby` or `aria-label` very well. These attributes are allowed to be used on <div> elements, but they won't do anything. This doesn't break any requirements, but it does fail best practice. (it would actually be bad if the `<div>` element did use the label, as that may 'overwrite' the text within the div.)

So if the `role="region"` is not used on an accordionpanel, it needs to also not have the `aria-labelledby` attribute.

**Comment by holloway** [comment]
Thanks to @synecdokey and @CalinDale this is now released as version 4.0.0. I'll close this ticket now @DraikoNick but feel free to comment when you try it. Cheers
