### ISSUE TITLE
Click again to minimize an accordion

### ISSUE THREAD

**Issue by ahlee42** [springload/react-accessible-accordion#330]
Hi, sorry if this is a dumb question but how do I make it so that when an accordion is expanded, I can click on that same accordion panel to close/contract that panel?

**Comment by transopticmedia** [comment]
<Accordion allowZeroExpanded>

Component API: allowZeroExpanded : boolean [optional, default: false]

**Comment by synecdokey** [comment]
Seems like this was answered already, closing :)
