### ISSUE TITLE
version change without release

### ISSUE THREAD

**Issue by sallymacnicholas** [springload/react-accessible-accordion#334]
👋 It looks like the version was updated in [this](https://github.com/springload/react-accessible-accordion/commit/c805a59348d16ab8d7d0b374042f93655e8546b2) commit but there was no new version release.

**Comment by holloway** [comment]
Hi @sallymacnicholas I don't understand. NPM seems to have version 4.0.0

![image](https://user-images.githubusercontent.com/620580/136095853-f784a567-14a9-469c-96d6-ab6c7686a900.png)

**Comment by holloway** [comment]
Ah that makes sense. Updated now. How does it look @sallymacnicholas @wspurgin ?

**Comment by sallymacnicholas** [comment]
Ahh yes, thanks @wspurgin for the clarification. Looks great, @holloway!
