### ISSUE TITLE
Feature for Accordion to auto collapse on mobile sizes

### ISSUE THREAD

**Issue by jrg4017** [springload/react-accessible-accordion#34]
It would be awesome if the accordion could have a property that allows the accordion to collapse all Accordion Items upon entering a certain screen width (i.e. for mobile and tablet screen sizes).

**Comment by vincentaudebert** [comment]
Hi @jrg4017 

Could you give a bit more context on the use case?
You would have few items pre open but if screen width < SIZE then you just close everything no matter what?

**Comment by vincentaudebert** [comment]
Closing due to no reply

If you are trying to achieve what I commented above you can do it externally using `activeItems` on the Accordion component.
