### ISSUE TITLE
Preparing React Accessible Accordion for React 18

### ISSUE THREAD

**Issue by holloway** [springload/react-accessible-accordion#341]
It seems that broadly speaking it will be compatible, but our generated ids will have to use the `useId` hook,

> it's even more important in React 18 because of how our streaming server renderer delivers HTML out-of-order. Solutions that may have worked previously, like using a counter to generate IDs, don't work in 18.0 because you can't rely on a consistent sequence. ([cite](https://github.com/reactwg/react-18/discussions/111))

We were using the counter to generate IDs approach, so we'll have to adopt `useId`.

Because we have React as a peerDep we'll have to detect if `useId` is available and fallback to our existing counter approach.

As such these autogenerated ids will change in a release of RAA for React 18.

Are there any other issues that we should address for React 18?

**Comment by trigunam** [comment]
We are also looking for React 18 support for accordions. @holloway is there a plan to merge this PR #342?

**Comment by holloway** [comment]
@trigunam yes, within a week if testing goes well.

**Comment by holloway** [comment]
@trigunam This has been published as 5.0.0. Please let me know if this works for you.

**Comment by trigunam** [comment]
It's working now. Thank you @holloway

**Comment by holloway** [comment]
Great, thanks!
