### ISSUE TITLE
v1.0.1 - Can't resolve 'uuid' in AccordionItem

### ISSUE THREAD

**Issue by DavidFreetly** [springload/react-accessible-accordion#36]
I upgraded from 0.5.0 to 1.0.1 this morning and I am getting this message.

./node_modules/react-accessible-accordion/dist/AccordionItem/accordion-item.js

Module not found: Can't resolve 'uuid' in '/test/node_modules/react-accessible-accordion/dist/AccordionItem'

**Comment by vincentaudebert** [comment]
Hi @DavidFreetly,

`uuid` got replaced by `consecutive`. I suspect your `node_modules` to haven't updated properly.
Could you please make sure you nuke the `node_modules` folder (or at least `/node_modules/react-accessible-accordion`) and reinstall please?

Let me know how you go after that. Thanks.

**Comment by DavidFreetly** [comment]
Hi @vincentaudebert,

I thought the same thing so I did these things:
- uninstalled the react-accessible-accordion
- blew away my node_modules folder
- cleared my npm cache....had to give the --force option to make it happen
- installed the react-accessible-accordion

So, I did those steps and I still get the same error.

I checked your github repo and I see the changes to the code but it's like the npm registry is giving me the wrong stuff back when I do the npm install.

I've downgraded back to 0.5.0 and got my code working again so you can close this if you would like.

**Comment by ryami333** [comment]
Thanks @DavidFreetly, looks like we might have mucked up our last build! We're going to re-publish immediately, so watch out for a new version in the next 10 mins or so.

**Comment by vincentaudebert** [comment]
Should be good now @DavidFreetly - version 1.0.2

Really sorry about that.
Let us know and I'll close issue if it's all good for you.

**Comment by DavidFreetly** [comment]
It's all good!
