### ISSUE TITLE
Controlled accordion

### ISSUE THREAD

**Issue by danbovey** [springload/react-accessible-accordion#39]
It's currently not possible to use this component with complete control over which items are expanded, which is a pretty common use case in a lot of React components. This line below, with the use of `activeItems` and `onChange` causes `onChange` to be called twice if a title is clicked.

https://github.com/springload/react-accessible-accordion/blob/07bb1cc8c9591bcd7fd071a547dd8b449cf0899f/src/Accordion/accordion.js#L46

Why would you need to inform the parent that the items have changed, when the parent component is giving you `activeItems`?

Solution: Make a `ControlledAccordion` component that uses `props.activeItems` to render expanded items, so there's no regression if anybody is using this functionality for a different use case.

**Comment by Mujaddadi** [comment]
Exactly Just came for the same reason. Can't control what to item to open at render time. I Dispatch an action after clicking the header of accordion item which fetched the data for that particular item. I need to open that accordion item when rendering after the redux store is updated.

**Comment by vincentaudebert** [comment]
Hi @danbovey yes this part of the code will be nuked once #43 is released. We prefer to focus on this instead of doing small fixes.
