### ISSUE TITLE
Make structure more flexible?

### ISSUE THREAD

**Issue by vincentaudebert** [springload/react-accessible-accordion#4]
At the moment the structure has to be:
```
Accordion
  AccordionItem
     AccordionTitle
     AccordionBody
```

It would be great to allow some other elements like `div` or anything in between.

At least between `Accordion` and the items as you might need to wrap items into another component.
For instance in my case I would like to wrap the Item into a `FormSection` from `redux-form`.

**Comment by vincentaudebert** [comment]
Started with this one https://github.com/springload/react-accessible-accordion/commit/69f93e584022a6ef25d56a44e2b8afb73d917a5c

**Comment by gbbauto** [comment]
Further, it seems that the minimum structure wants to be:

Accordion
  AccordionItem
     AccordionTitle
     AccordionBody
  AccordionItem
     AccordionTitle
     AccordionBody

...with at least 2 AccordionItem children.

My requirement is a single AccordionItem and this results in this warning:

Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Accordion`, expected an array.

Would love to see my use case supported (it current works fine with warning).

**Comment by vincentaudebert** [comment]
@gbbauto You should be alright with `v0.3.0` now :)
Thanks for your feedback.
