### ISSUE TITLE
Missing prop

### ISSUE THREAD

**Issue by ecastroItexico** [springload/react-accessible-accordion#40]
Given the actual behavior of the accordion still missing a prop to expand only from the arrow button since is required to put some buttons in the header

**Comment by vincentaudebert** [comment]
Any chance you would have an example code to illustrate what you mean?

**Comment by ryami333** [comment]
Sorry @ecastroItexico - I'm going to close this defect. Happy to re-open if you're able to elaborate a little.

Cheers!
