### ISSUE TITLE
Isomorphic / Server Side Rendering - Prop `id` did not match

### ISSUE THREAD

**Issue by HPieters** [springload/react-accessible-accordion#41]
When using react-accessible-accordion in combination with Next.js I get the following warning on occasion `Prop 'id' did not match. Server: "accordion__title-X" Client: "accordion__title-X"`. I have multiple pages with different react-accessible-accordions, and this is what causes the issue I believe. The server uuid is mismatched with the client uuid.

Would it be possible to add a `ResetIdCounter` similar to [react-tabs]( https://github.com/reactjs/react-tabs)? Or is there already a solution I am unaware of?

**Comment by ryami333** [comment]
Gidday there @HPieters - sorry for the delay in getting back to you. We've been scratching our head about this one. Is there any way that you could create us a minimal repo to demonstrate the issue you're having? We aren't Next users, so we're not really too sure how the average user might use RAA in combination with it.

Thanks for the issue :)

**Comment by HPieters** [comment]
@ryami333 No problem, I made a very quick demo project here https://github.com/HPieters/next-accordion-example. Just `npm i` and `npm run dev` to start. The result (for me  in chrome, you do need to refresh once) is the following:

<img width="556" alt="screen shot 2018-02-15 at 18 14 39" src="https://user-images.githubusercontent.com/2362116/36270488-1f07bdb2-127c-11e8-8933-d1e79a2c4d61.png">

The warning is caused by [nextUuid / consecutive](https://github.com/springload/react-accessible-accordion/blob/07bb1cc8c9591bcd7fd071a547dd8b449cf0899f/src/AccordionItem/accordion-item.js#L8) because on refresh the browser consecutive is empty and consecutive will start at 0, however the server memory will still be intact from previous sessions and will hold some arbitrary higher number.

**Comment by ryami333** [comment]
That's excellent, thanks for the reproducible case and the investigation. We'll certainly look into this, but if it's like you describe and it's due to some inconsistency between server and client-side data then I don't really know how we would fix this - it seems like it's just an unfortunate consequence of the framework's requirement that they must match for some reason.

**Comment by ryami333** [comment]
@HPieters - would it help if we exposed some method like `resetIds` that you could use in a route-change hook?

### Pseudo-code warning - don't copy and paste
```
import { resetIds } from 'react-accessible-accordion';
import { onRouteChange } from 'isomorphic-framework';

onRouteChange(resetIds);
```

It's the only way I can think of that would keep this library agnostic of the framework in which it's used. We would not want to hard-code in any awareness of particular frameworks, including Next.

**Comment by HPieters** [comment]
@ryami333 Yes this would solve the issue, a similar solution is provided by [react-tabs](https://github.com/reactjs/react-tabs#api) called resetIdCounter.

**Comment by ryami333** [comment]
Cool - we can definitely add this feature. Watch out for our new release, coming soon.

**Comment by vincentaudebert** [comment]
And it's alive!
Thanks heaps @ryami333 for the awesome work!

https://www.npmjs.com/package/react-accessible-accordion v2.0.0

**Comment by ryami333** [comment]
@HPieters, you should now be able to `import { resetNextUuid } from 'react-accessible-accordion'`. Let us know how you get on with the upgrade 😀

**Comment by HPieters** [comment]
@ryami333 It works, thank you! (Sorry for the late reply, holidays and deadlines ;) ). I also updated the test repo for future reference [https://github.com/HPieters/next-accordion-example](https://github.com/HPieters/next-accordion-example).

**Comment by Wisdom0063** [comment]
Make sure the component is mounted before you render that part.
something like:
import TinyMCE from "react-tinymce";
import { Component } from "react";
class Editor extends Component {
  constructor(props) {
    super(props);
    this.state = {
      mounted: false
    };
    this.handleEditorChange = this.handleEditorChange.bind(this);
  }
  componentDidMount() {
    this.setState({ mounted: true });
  }
  handleEditorChange(e) {
    console.log(e.target.getContent());
  }
  render() {
    let TinyEditor =
      this.state.mounted === true ? (
        <TinyMCE
          content="<p>This is the initial content of the editor</p>"
          config={{
            plugins: "autolink link image lists print preview",
            toolbar:
              "undo redo | bold italic | alignleft aligncenter alignright"
          }}
          onChange={this.handleEditorChange}
        />
      ) : (
        ""
      );
    return <div>{TinyEditor}</div>;
  }
}

export default Editor;

**Comment by dcheglakov** [comment]
Sorry for resurrecting this issue. I've tried `resetNextUuid()` it resets id, but I still have an error in the developer console.

```
Warning: Prop `id` did not match. Server: "accordion__heading-raa-0" Client: "accordion__heading-raa-1"
    at div
    at AccordionItemButton (webpack-internal:///./node_modules/react-accessible-accordion/dist/es/index.js:753:29)
    at Consumer (webpack-internal:///./node_modules/react-accessible-accordion/dist/es/index.js:598:5)
    at AccordionItemButtonWrapper
    at div
    at AccordionItemHeading (webpack-internal:///./node_modules/react-accessible-accordion/dist/es/index.js:845:5)
    at Consumer (webpack-internal:///./node_modules/react-accessible-accordion/dist/es/index.js:598:5)
    at AccordionItemHeading...
```

Here is my code

```jsx
import PropTypes from 'prop-types'
import {
  Accordion,
  AccordionItem,
  AccordionItemHeading,
  AccordionItemButton,
  AccordionItemPanel,
  resetNextUuid,
} from 'react-accessible-accordion'

export default function Faq({ title, faq }) {
  resetNextUuid()
  return (
    <div className="py-32">
      <h2 className="pb-20 text-center">
        {title} <span className="text-red">FAQ</span>
      </h2>
      <Accordion>
        {faq.map((item, index) => (
          <AccordionItem key={item.id}>
            <AccordionItemHeading className="py-6 border-b border-suva-grey border-opacity-50">
              <AccordionItemButton>
                <h4>
                  <span className="pr-8 text-red">{`0${index + 1}`}</span>
                  {item.question}
                </h4>
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel>
              <p className="py-8 text-suva-grey lg:w-11/12">{item.answer}</p>
            </AccordionItemPanel>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  )
}

Faq.propTypes = {
  title: PropTypes.string.isRequired,
  faq: PropTypes.array.isRequired,
}

```

What I'm doing wrong?

**Comment by vldnovikov** [comment]
Hi @dcheglakov, you need just add `uuid` to `AccordionItem`.
So it should look like this:

```
import PropTypes from 'prop-types'
import {
  Accordion,
  AccordionItem,
  AccordionItemHeading,
  AccordionItemButton,
  AccordionItemPanel,
  resetNextUuid,
} from 'react-accessible-accordion'

export default function Faq({ title, faq }) {
  resetNextUuid()
  return (
    <div className="py-32">
      <h2 className="pb-20 text-center">
        {title} <span className="text-red">FAQ</span>
      </h2>
      <Accordion>
        {faq.map((item, index) => (
          <AccordionItem key={item.id} uuid={item.id}>
            <AccordionItemHeading className="py-6 border-b border-suva-grey border-opacity-50">
              <AccordionItemButton>
                <h4>
                  <span className="pr-8 text-red">{`0${index + 1}`}</span>
                  {item.question}
                </h4>
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel>
              <p className="py-8 text-suva-grey lg:w-11/12">{item.answer}</p>
            </AccordionItemPanel>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  )
}

Faq.propTypes = {
  title: PropTypes.string.isRequired,
  faq: PropTypes.array.isRequired,
}
```

**Comment by dcheglakov** [comment]
@vldnovikov thank you. It helped.
