### ISSUE TITLE
CSS Missing

### ISSUE THREAD

**Issue by mschwartz** [springload/react-accessible-accordion#42]
IMO, it would be a good idea to provide a .css in the distribution.  When you use npm to install this, there is no .css installed.  This forces the user to look into the demo sources and its .css and to basically clone it in the project's css.

Ideally, you'd include the react-accessible-accordion/dist/accordion.min.css (or whatever) and then expand on the default rules with project specific ones.

**Comment by vincentaudebert** [comment]
@mschwartz Yes it's planned for the next version. Just focusing on store management for now. Thanks for the reminder.

**Comment by vincentaudebert** [comment]
FYI, it will be added in the next minor release

**Comment by ingro** [comment]
Hello, a css file was included inside the dist folder in 2.0.0, is gone in 2.1.0 though

**Comment by vincentaudebert** [comment]
Fixed in `2.2.0`

Thanks for your patience
