### ISSUE TITLE
Add further keyboard controls

### ISSUE THREAD

**Issue by samanthaksanders** [springload/react-accessible-accordion#57]
Currently can navigate using tab, however we could build on this and add further keyboard support.

For reference on expected controls
https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html#kbd_label

**Comment by ryami333** [comment]
Implemented on `next` branch. Watch [here](https://github.com/springload/react-accessible-accordion/issues/168) and [here](https://github.com/springload/react-accessible-accordion/pull/188) to track progress of the associated upcoming release.
