### ISSUE TITLE
Programmatically  open accordion

### ISSUE THREAD

**Issue by jeanpokou-vinvox** [springload/react-accessible-accordion#62]
is it possible to open the accordion progammatically

**Comment by vincentaudebert** [comment]
Hi @jeanpokou-vinvox ,

Yes you can use the `expanded` property on `AccordionItem` to expand the item "on the fly".
https://github.com/springload/react-accessible-accordion#accordionitem

**Comment by casoetan** [comment]
This does not work for me. Its only set on initial load, programmatically trying to updated it fails.

**Comment by jeanpokou-vinvox** [comment]
Same here, but I was able to achieve the same by changing the css class this way. it's not pretty but works

``` javascript 
// assuming you have only one accordion (1) 
const accordion-item  = #accordion__body-1;
const accordion-item-title  = #accordion__title-1;

// open accordion 
document.querySelector(accordion-item).classList.remove('accordion__body--hidden');
document.querySelector(accordion-item).setAttribute('aria-hidden', true);
document.querySelector(accordion-item-title).setAttribute('aria-selected', false); 

// close accordion 
document.querySelector(accordion-item).classList.add('accordion__body--hidden');
document.querySelector(accordion-item-title).setAttribute('aria-selected', true);
document.querySelector(accordion-item).setAttribute('aria-hidden', false);
```
If you have multiple accordion in a component you can wrap it inside a loop 
```javascript 
for ( let i = 0; i < 3; i++ ) {
   const accordion-item  = #accordion__body-+i;
   const accordion-item-title  = #accordion__title-+ i;
   ...
   ...
}
```

**Comment by vincentaudebert** [comment]
We're going to investigate this ASAP. Thanks for the feedbacks 👍

**Comment by ryami333** [comment]
Gidday there @jeanpokou-vinvox, thanks for the issue. We created this sandbox to try and demonstrate a working programmatically controlled Accordion and we've not been able to reproduce any issues. https://codesandbox.io/s/4zqrxnp4z4

Would you mind please trying to update that sandbox to demonstrate the problem that you're experiencing?

**Comment by monting** [comment]
Using `expanded` prop/state like @ryami333  works for me.

But, you need to remember to change the `expanded` state on user interaction too, otherwise react won't update if the old `expanded` state is the same as new `expanded` state. Might have been why it wasn't working for some folks.

E.g.
```jsx
<Accordion onChange={this.changeAccordion}>
```

```javascript
  changeAccordion = (ordinal) => {
    this.setState((oldState) => {
      if (oldState.expanded == ordinal) { 
        return {expanded: null};  // user closed accordion
      } else {
        return {expanded: ordinal};
      }
    })
  }
```
