### ISSUE TITLE
Accordion Not working in IE11

### ISSUE THREAD

**Issue by mantrawadirama** [springload/react-accessible-accordion#63]
Hi,
Accordion not loading in IE 11. May I know if there is workaround for this.

Thanks
Rama

**Comment by ryami333** [comment]
Gidday Rama, could you please send us a snippet of your code so that we can see your particular use-case? I am using this package myself in a large scale project, and our testers haven't reported any issues with out accordions on IE11. Any console errors?

**Comment by vincentaudebert** [comment]
Hi @mantrawadirama 

We just fixed the demo. We bumped to 16.2 without adding the needed polyfills.
Could you please confirm that by `not loading in IE11` you were talking about our demo page?

Thanks.
