### ISSUE TITLE
Use MouseOver Event to drive accordion

### ISSUE THREAD

**Issue by Coderkobe** [springload/react-accessible-accordion#65]
Now i use your react-accessible-accordion, i found the default event is click. if i want to use mouseover but not click. how should i do?

**Comment by ryami333** [comment]
Gidday @Coderkobe, thanks for your query and sorry for the delay. Additional events are not currently supported by this library. Aria spec does not dictate that an accessible accordion element be have its state toggled by mouse/hover events, so we do not have any plans to implement this feature at this stage.

Thanks though for your input, and we'll keep it in mind.
