### ISSUE TITLE
Upgrading to 2.3.0 breaks build

### ISSUE THREAD

**Issue by mbenjamin618** [springload/react-accessible-accordion#76]
I am using React V16.3.1 from a create-react-app and the version 2.3.0 release causes the build to break with the error: `babelhelpers is not defined`

Workaround: roll back to 2.2.1 due to this error

**Comment by vincentaudebert** [comment]
Hi @mbenjamin618 

Thanks for raising the issue. It's all fixed in `v2.3.1`. Sorry about that.
