### ISSUE TITLE
babelHelpers is not define error:

### ISSUE THREAD

**Issue by ASH-khan** [springload/react-accessible-accordion#77]
1034 | 
  1035 | var createReactContext = unwrapExports(lib);
  1036 | 
> 1037 | **var _typeof = typeof Symbol === "function" && babelHelpers.typeof(Symbol.iterator) === "symbol" ? function (obj) {**
  1038 |   return typeof obj === 'undefined' ? 'undefined' : babelHelpers.typeof(obj);
  1039 | } : function (obj) {
  1040 |   return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj === 'undefined' ? 'undefined' : babelHelpers.typeof(obj);

**Comment by ASH-khan** [comment]
i installed the lib and all the dependencies but getting this error.
please advise i am missing something.

thanks 
Ash

**Comment by ASH-khan** [comment]
@vincentaudebert thank you for your quick response.
waiting for the new patch.
Ash:)

**Comment by vincentaudebert** [comment]
@ASH-khan it's all fixed in `v.2.3.1` now

Thanks for raising the issue. Enjoy.
