### ISSUE TITLE
Investigate how to bump to unstated 2.0

### ISSUE THREAD

**Issue by vincentaudebert** [springload/react-accessible-accordion#79]
`unstated` just released 2.0 and it requires some code modifications to work.

**Comment by vincentaudebert** [comment]
Ok I think I've located the origin of the bug.

https://github.com/springload/react-accessible-accordion/blob/366f6251a0e1e7430dcff5f998c141310e666161/src/AccordionItem/accordion-item.js#L21

We basically trigger a `setState` when the component hasn't been mounted yet. This is anti pattern.
I reckon we need to create a HOC and use it here: https://github.com/springload/react-accessible-accordion/blob/366f6251a0e1e7430dcff5f998c141310e666161/src/AccordionItem/accordion-item-wrapper.js#L35

So we end up populating the AccordionItem only once it's actually added to the state. That way we won't need `componentWillMount` anymore and the bug should be gone.

**Comment by ryami333** [comment]
Long story short, it looks like the biggest blocker here is that `setState` is now async in unstated, so we've got to update our tests to cater for it. May need to refactor our container methods to return promises so we can test them properly.

**Comment by ryami333** [comment]
Closed by https://github.com/springload/react-accessible-accordion/pull/87
