### ISSUE TITLE
How to add onClick without overriding the existing click events?

### ISSUE THREAD

**Issue by ChCosmin** [springload/react-accessible-accordion#84]
I use the accordion version where only 1 item can be expanded at a time. I also want to add an onClick event on the tabs(that are the AccordionItemTitle tags i presume) that changes the state to something else. if i add the onclick event, the expand on click event is not working anymore. 

Where can i add my custom onClick event to go together with the existing ones from this component? Thanks :)

**Comment by vincentaudebert** [comment]
I will investigate how to add this possibility in the next few days hopefully.
Thanks for your issue. Feel free to make a PR if you want to speed up things :)

**Comment by vincentaudebert** [comment]
@ChCosmin Have you thought about using the `onChange` function on `Accordion` component? This is triggered on every action on the accordion (open/close items)

**Comment by vincentaudebert** [comment]
Closing as I think this can be dealt with `onChange` function. Will reopen if I get a good example of what needs to be achieved.
