### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by vincentaudebert** [springload/react-accessible-accordion#97]
Following #93 it would be great to support TypeScript typing.

This is an issue to be picked by someone outside the core crew as we don't have enough experience with TypeScript.

**Comment by scottdj92** [comment]
Hey, I've taken a crack at this and submitted a PR: #138. it'll be shipped with this package, but if you'd like me to move it to DefinitelyTyped, I can do that too.

**Comment by ryami333** [comment]
Closed by https://github.com/springload/react-accessible-accordion/pull/141
